### ISSUE TITLE
Suggestions on complex gemm?

### ISSUE THREAD

**Issue by zhcui** [libxsmm/libxsmm#227]
Dear developers,

A project that I am doing is related to complex gemm and maybe mixed type stuff.
I noticed that there is a previous issue https://github.com/hfp/libxsmm/issues/97
and at that time the complex type was not a short-term goal.

What about now, is libxsmm going to support complex/mixed variables?
If not, do you have any suggestions on how to use libxsmm_dgemm to finish a complex gemm?

Best,
Zhihao

**Comment by hfp** [comment]
> What about now, is libxsmm going to support **complex** variables?

It is of higher interest now and I will look into this. I cannot commit to a milestone (yet) as there is some research needed. The closest possible milestone would be v2.0, but this is only possible if research concludes to implement with a real-valued kernel.

> What about now, is libxsmm going to support **mixed** variables?

There is some experimental code for low-precision gemm, but it certainly lacks a fall-back implementation - or differently said: only AVX-512 targets are supported (and somewhat different limitations depending on the subtarget aka Xeon vs Xeon Phi), and perhaps limitations to the matrix extents apply as well (must be multiples of the vectorwidth).

>  If not, do you have any suggestions on how to use libxsmm_dgemm to finish a complex gemm?

There is no immediate solution to reuse a real kernel such as dgemm to perform a complex-valued gemm (zgemm). A solution is rather attributed to the above mentioned research.

**Comment by zhcui** [comment]
Thanks for your reply.
Happy to see it's of higher interest, and look forward to the new version ^^

**Comment by hfp** [comment]
Closing this issues, but recorded as a [long-term issue](https://github.com/libxsmm/libxsmm/wiki/Development#longer-term-issues) (somewhat recurring request).
