### ISSUE TITLE
Rely on scratch buffer rather than fixed-size/local array

### ISSUE THREAD

**Issue by hfp** [libxsmm/libxsmm#357]
There is no specific build option needed; even a debug build is fine (`make DBG=1`). The example fails for every target (`LIBXSMM_TARGET`). The example works just fine with v1.14.

**Comment by hfp** [comment]
This is caused by spilling over in `A_ptrs` and `B_ptrs` when assembling batch-reduce input. The code uses hard-coded, i.e., fixed-size arrays with 1024 entries. Perhaps these pointer need to be migrated into the handle and sized according to the kernel-size (may also depend on blocking factor, etc.).

**Comment by hfp** [comment]
Reduced kernel-size (1babea0). However, array may be migrated into handle or an error check should be upfront.

**Comment by hfp** [comment]
This is still present in our code base, but may not gate v1.17. It is desired to bail/error-out for case exceeding the (hard-coded) limit.

**Comment by alheinecke** [comment]
fixed as this code was removed
