### ISSUE TITLE
LSTM/UPD/FP32 wrong result

### ISSUE THREAD

**Issue by hfp** [libxsmm/libxsmm#488]
For example, `lstmdriver_nc_ck_f32 1 2 256 2048 2048 5 32 32 32` produces wrong results independent of the compiler (version/vendor, etc).

**Comment by hfp** [comment]
The bias is correct, however, both delta and delta recurrent weights are incorrect.

**Comment by hfp** [comment]
It seems to be also wrong independent of the (runtime-)code (LIBXSMM_TARGET).

**Comment by HiSPEET** [comment]
Hi, is this issue specific to any branch? Just today I created a FP32 version of an FP64 kernel using LIBXSMM for tensor-product matrix multiplication. While the latter agrees well with a reference routine (e.g. 1e-12), the FP32 version differs considerably from the FP32 reference (e.g. 1e-2). This happens with the current master as well as release branches with Linux/MacOS Intel and GNU compilers. Can this be related or should I look for other reasons?

Jörg

**Comment by alheinecke** [comment]
This is a problem specific to the LSTM cell. What you are describing doesn't sound like a bug / problem at first sight (without seeing any code). The question is simply how long your inner product is and how large your inputs are.  FP accumulation is not associative (and I guess that your reference is not implementing the same order as LIBXSMM), so if your numbers are ~1e4, then an absolute error of 1e-2 is perfectly fine.  Best example is our simple kernel tester in samples/xgemm. When running with beta=1 and 1000+ iterations the error is huge as the accumulation chain is very long:

./kernel 32 32 32 32 32 32 1 1 0 0 0 0 nopf SP nobr 1 0 1 0 -> max. error: 0.000002                  // ~32 * 0.0000001
./kernel 32 32 32 32 32 32 1 1 0 0 0 0 nopf SP nobr 1 0 100 0  -> max. error: 0.002625             // ~3200 * 0.0000001
./kernel 32 32 32 32 32 32 1 1 0 0 0 0 nopf SP nobr 1 0 10000 0 -> Total Max Error 0.335938   //  ~320000 * 0.0000001

Your FP64 difference indicates ~1000 accumulations (1e-12 vs 1e-15) as well so everything looks OK.

**Comment by hfp** [comment]
Indeed, the problem tracked here is specific to, e.g., `lstmdriver_nc_ck_f32 1 2 256 2048 2048 5 32 32 32` where POT sizes appear or the `2048` in particular. Further details need investigation.

**Comment by HiSPEET** [comment]
Agreed. I will look closer into that, but it seems you are right with the accumulation effect. I was applying a chain of six 8x8 random matrices to random operands, all bounded between 0 and 1. With each matrix multiplication the deviation gained roughly half an exponent, i.e. 1e-6 after one and 5e-4 after 6. Increasing the matrix size made it worse, leading to a deviation of ca 1e0 with 32x32 matrices.

I found this effect when comparing to „naive“ reference implementation. It does not mean that the latter are better. But the effort to use FP32 instead of FP64 for preconditioning may be in vain.

Jörg

**Comment by HiSPEET** [comment]
Addendum: In the real application FP32 worked nicely. Maybe, my test case was too hard ;)
Thus, you may safely neglect my comment.

Jörg

**Comment by alheinecke** [comment]
with Intel Compiler: icc 19.1.1, icpc 19.1.1, and ifort 19.1.1 & avx512 it works fine:

[lstmdriver]$ OMP_NUM_THREADS=1 sde64 -skx -- ./lstmdriver_nc_ck_f32 1 2 256 2048 2048 5 32 32 32
##########################################
#          Setting Up (Common)           #
##########################################
PARAMS: N:256  C:2048  K:2048  T:5
PARAMS: ITERS:1
SIZE Weight (MB):      16.00 MiB
SIZE Input (MB):       2.00 MiB
SIZE Hidden State:       2.00 MiB
##########################################
#         Computing Reference ...        #
##########################################
##########################################
#      Computing Reference ... done      #
##########################################

##########################################
#      Setting Up  (custom-Storage)      #
##########################################
##########################################
#   Correctness - UPD (custom-Storage)   #
##########################################
Delta weight
L1 reference  : 57110.42401673309359466657
L1 test       : 57110.43592957055079750717
L2 abs.error  : 0.000397569564039206143832
L2 rel.error  : 1797.000192507226756788440980
Linf abs.error: 0.000000989064574241638184
Linf rel.error: 1357.730957031250000000000000
Check-norm    : 0.000012171600706097139731
Delta recurrent weight
L1 reference  : 66779.27160784434818197042
L1 test       : 66779.3325715083337854594
L2 abs.error  : 0.004826810770839360179019
L2 rel.error  : 2492.011995361399840476224199
Linf abs.error: 0.000012416392564773559570
Linf rel.error: 1934.519856770833257542108186
Check-norm    : 0.000122655950841362647004
Delta bias
L1 reference  : 1711.428256667801178991795
L1 test       : 1711.428490464728383813053
L2 abs.error  : 0.000428285454702578144426
L2 rel.error  : 0.931782594165684985298981
Linf abs.error: 0.000033617019653320312500
Linf rel.error: 0.779861329971635708346867
Check-norm    : 0.000009452873323568429046

**Comment by alheinecke** [comment]
also with gcc is works perfectly when specifying "AVX=3" during make.... seems like on top some compiler feature detection is broken.... so the issue seems to be AVX/AVX2 code and not compiler related.

**Comment by alheinecke** [comment]
@egeor: please have a look why https://github.com/hfp/libxsmm/commit/624373f5e9802d0326cf531a86fb7191e93ef02d fixes the problem... for AVX2, this sounds strange...

**Comment by hfp** [comment]
@alheinecke GCC (for quite some time) had disabled dynamic dispatch of Intrinsic based code-paths (due to recurring issues from users about outdated Binutils like old Linux distributions). I have (re-)enabled [dispatching Intrinsic based code-paths](https://github.com/hfp/libxsmm/commit/49a8427378b75813d39be556d8b7df8a382263ff) for our environment, i.e., newer GCCs (when newer Binutils are source'd).

**Comment by hfp** [comment]
I tested with current master/main revision and the issue appears to be fixed.

**Comment by alheinecke** [comment]
still open

**Comment by alheinecke** [comment]
disabled unit test and rnn/lstm will be soon removed from code base -> issue closed by definition
