### ISSUE TITLE
memory allocation issues

### ISSUE THREAD

**Issue by hfp** [libxsmm/libxsmm#489]
There are two suspicions:

1.	Memory for data (to be operated on) causing slower execution when compared to `_mm_malloc`.
2.	Memory for JITted code (hoisted).

There is some previous [issue](https://github.com/hfp/libxsmm/issues/383) related to the first issue (see above), which was resolved at that time.

**Comment by hfp** [comment]
The history of https://github.com/hfp/libxsmm/commits/master/samples/deeplearning/sparse_adagrad_fused may help to unveil a reproducer for the first problem.

**Comment by hfp** [comment]
Memory allocations for data (`libxsmm_[aligned_]malloc`):

* The default behavior is now changed to rely on `_mm_malloc` and `_mm_free`, which are likely macros mapped to compiler runtime library functions like `aligned_malloc` or similar. The actual memory allocation mechanism of `_mm_malloc` can depend on compiler and flags.
* The behavior of `_mm_malloc` was investigated and compared to `libxsmm_[aligned_]malloc` (as previously implemented)
  * Underlying `__GI___mmap64` received the same flags except LIBXSMM's routine explicitly requested huge pages.
  * The `_mm_malloc` routine likely receives huge pages as well (implicitly based on Linux' THP).
* Previous implementation of `libxsmm_[aligned_]malloc` can be restored (`LIBXSMM_MALLOC_MMAP`).

**Comment by alheinecke** [comment]
fixed as the code has been removed
