### ISSUE TITLE
libxsmm_reset_x86_gp_reg_mapping in libxsmm_generator_packed_spgemm_csc_bsparse_aarch64

### ISSUE THREAD

**Issue by FreddieWitherden** [libxsmm/libxsmm#535]
Looking through `libxsmm_generator_packed_spgemm_csc_bsparse_aarch64`  I see:

https://github.com/hfp/libxsmm/blob/master/src/generator_packed_spgemm_csc_bsparse_aarch64.c#L97

which calls `libxsmm_reset_x86_gp_reg_mapping`.  This is somewhat unusual at first glance given the routine is for aarch64.  Is this is bug, or should the gp reg mapping routine be renamed to avoid the x86 moniker if it is indeed generic?

**Comment by alheinecke** [comment]
Yes, two renaming are needed as it is indeed generic, let me take care this in beginning of November:
-> x86 should go away as it is generic 
-> libxsmm_gp_reg_mapping -> libxsmm_gemm_gp_reg_mapping (or similar)

**Comment by FreddieWitherden** [comment]
I think this is now resolved?

**Comment by alheinecke** [comment]
yes
