### ISSUE TITLE
Dense MM performance for AARCH64

### ISSUE THREAD

**Issue by FreddieWitherden** [libxsmm/libxsmm#537]
I am currently in the process of extending the sparse register kernels to AARCH64.  Before doing so I wanted to get a baseline for how well the dense AARCH64 kernel in libxsmm are working.  Using the current Git master on a 2 VCPU AWS machine (t4g.small) on Ubuntu 20.04 I obtain the following with some level of reproducibility:
```
~/libxsmm/samples/pyfr$ ./pyfr_driver_asp_reg ./mats/p3/tet/m132-sp.mtx 48000 1000
CSR matrix data structure we just read:
rows: 20, columns: 60, elements: 1092
computing golden solution...
...done!
computing libxsmm (A sparse) solution...
...done!
computing BLAS (A dense) solution...
...done!
max error beta=0 (libxmm vs. gold): 0.000000
max error beta=1 (libxmm vs. gold): 0.000000
max error beta=0 (dense vs. gold): 0.000000
max error beta=1 (dense vs. gold): 0.000000
time[s] LIBXSMM (RM, M=20, N=48000, K=60, beta=0): 0.019950
GFLOPS  LIBXSMM (RM, M=20, N=48000, K=60, beta=0): 5.254675 (sparse)
GFLOPS  LIBXSMM (RM, M=20, N=48000, K=60, beta=0): 5.774368 (dense)
GB/s    LIBXSMM (RM, M=20, N=48000, K=60, beta=0): 1.539831
time[s] LIBXSMM (RM, M=20, N=48000, K=60, beta=1): 0.019981
GFLOPS  LIBXSMM (RM, M=20, N=48000, K=60, beta=1): 5.246593 (sparse)
GFLOPS  LIBXSMM (RM, M=20, N=48000, K=60, beta=1): 5.765486 (dense)
GB/s    LIBXSMM (RM, M=20, N=48000, K=60, beta=1): 1.921829
time[s] MKL     (RM, M=20, N=48000, K=60, beta=0): 0.005533
GFLOPS  MKL     (RM, M=20, N=48000, K=60, beta=0): 20.820270
GB/s    MKL     (RM, M=20, N=48000, K=60, beta=0): 6.940090
time[s] MKL     (RM, M=20, N=48000, K=60, beta=1): 0.005421
GFLOPS  MKL     (RM, M=20, N=48000, K=60, beta=1): 21.250663
GB/s    MKL     (RM, M=20, N=48000, K=60, beta=1): 7.083554
```
where the reference results are being computed by OpenMP-enabled OpenBLAS.  For a small dense matrix OpenBLAS is outperforming the JIT'ed libxsmm kernel by a factor of ~3.5 or so.  Is this kind of discrepancy to be expected given the current status of the code?  (Note libxsmm says sparse, but it ends up JIT'ing a dense kernel as the sparse register routines are not yet coded up.)

**Comment by alheinecke** [comment]
Will this issue be fixed when merging #543?

**Comment by FreddieWitherden** [comment]
The situation is better, however, performance is still not quite where it should be.

The core kernels themselves are fine and can get a very high fraction of peak when the strides are small.  For example, `mats/p4/tet/m132-sp.mtx` can get ~18 GFLOP/s DP on a single N1 core when the matrix size is 48 (smallest supposed by the driver).  Increasing this to 48,000 performance drops to just ~10.5 GFLOP/s whereas OpenBLAS can do ~14.4 GFLOP/s for the same matrix.  This is a compute limited kernel with modest bandwidth requirements (<< available single core bandwidth).

This indicates that the kernel may not be in good standing with the cache hierarchy/memory controller/pre-fetchers.

**Comment by FreddieWitherden** [comment]
On the SVE side I am also observing poor performance for the core kernels on an actual A64FX core.  As an example:
```
LIBXSMM_TARGET=A64FX ./kernel 8 60 35 8 35 8 1 1 0 0 0 0 nopf DP nobr 1 0 100000 0
------------------------------------------------
RUNNING (8x35) X (35x60) = (8x60), DP, BR=1
------------------------------------------------
function pointer address: 400029f11000
0.000086s for creating jit
4.204782s for C
0.799090 GFLOPS for C
0.220276s for libxsmm
15.253561 GFLOPS for libxsmm
max. error: 0.000000
------------------------------------------------
```
where peak is ~64 GFLOP/s (still unsure if the chip I am running on is 2 or 2.2 GHz).  This is a size which should deliver strong performance; on an x86 CPU with a single AVX-512 FMA unit I find:
```
./kernel 8 60 35 8 35 8 1 1 0 0 0 0 nopf DP nobr 1 0 100000 0
------------------------------------------------
RUNNING (8x35) X (35x60) = (8x60), DP, BR=1
------------------------------------------------
function pointer address: 7ff7b1947000
0.000148s for creating jit
0.542643s for C
6.191912 GFLOPS for C
0.048959s for libxsmm
68.629330 GFLOPS for libxsmm
max. error: 0.000000
------------------------------------------------
``
which is basically peak given the chip is clocked around 4.4 GHz.

Going from 8 => 32 as `./kernel 8 60 35 8 35 8 1 1 0 0 0 0 nopf DP nobr 1 0 100000 0` increases the SVE performance to ~41.5 GFLOP/s but this is still way below peak (and a larger size than we can practically use in PyFR).

Looking through the architecture manual for the A64FX it appears as if we have an 11 cycle load to use latency for vectors, and a 9 cycle FMA latency.  Plus a relatively small OOE window.  This could be a nuisance.

**Comment by hfp** [comment]
> ```
> LIBXSMM_VERSION: master-1.16.3-1969 (25216945)
> X86_64/DP    TRY    JIT    STA    COL
> ```
> 
> which references X86 [...] although they are clearly ARM binaries:

This is fixed (2e89786fe108cc04a50311840c6dda0d10180d81).

**Comment by alheinecke** [comment]
We realized that on A64FX the latencies (as you write) are very high and I hope recall correctly that the current kernel doesn't do an aggressive unrolling in N dimension. When M=8 we have only one vector in SIMD dimension, so we have 30 register (N=30) we could use to hide FMA latencies... However the machine then needs to be able to handle 2 bdcasts and 2 FMA in the same cycle to hit close to peak.

Is the small M coming as for pyfr we need to flip M/N?

**Comment by FreddieWitherden** [comment]
Right, PyFR wants to do row major A*B where A = constant and B is long.  Since the routines are CM we flip M/N and the A/B arguments.  We currently do not pre-transpose A (even though we could so we'd go from an 'NN' routine to an 'NT' routine) although am unsure if the kernel would prefer it or not.

Looking at the A64FX uarch guide (https://raw.githubusercontent.com/fujitsu/A64FX/master/doc/A64FX_Microarchitecture_Manual_en_1.3.pdf) I believe it is possible to issue two loads in a cycle and two FMA's in a cycle, but I do not think that leaves anything for addressing.

Another 'quirk' is that it does not seem to pick up on the fact that `eor zn, zn, zn` is a zeroing idiom and so you end up with a false dependency on zn.  My in-cache sparse routines got 25% slower when I nop'ed out all of my loads with eor's!

**Comment by breuera** [comment]
Here are a few single-core performance measurements (C+=AB) using revision 4ac333be5260efcef592eb13bc48cfd3f6899148.

Systems are:

- Graviton2: Amazon EC2 c6g.metal instance having a single Graviton2 processor (Neoverse N1). The processor clocks at a frequency of 2.5GHz and has 64 cores. Each of the cores has two 128-bit ASIMD pipelines, where a single pipeline has a throughput of one 128-bit FMLA-instruction per cycle. This results in a theoretical peak performance of 40.0 FP32- GFLOPS or 20.0 FP64-GFLOPS per core.
- Altra: Oracle Compute Infrastructure BM.Standard.A1.160 instance using Oracle Linux 7.9. The instance had two Ampere Altra Q80-30 processors (Neoverse N1). The processors have a clock frequency of 3.0 GHz. Each of the node's 160 cores has two 128-bit ASIMD pipelines. A single pipeline has a troughput of one 128-bit FMLA-instruction per cycle, resulting in a theoretical peak of 60.0 FP32-GFLOPS or 30.0 FP64-GFLOPS per core.
- A64FX: A single A64FX-node of the Isambard 2 UK National Tier-2 HPC Service. An A64FX-node has a single Fujitsu A64FX processor operating at 1.8GHz. Each of the processor's 48 cores has two 512-bit SVE-pipelines. A single pipeline can perform one 512-bit FMLA-instruction per cycle, resulting in a theoretical peak performance of 115.2 FP32- GFLOPS or 57.6 FP64-GFLOPS per core.
- M1: 2020 Mac Mini with an M1 processor. M1 features four Firestorm performance cores and four Icestorm efficiency cores. The Firestorm cores operate at a presumed frequency of 3.2GHz and each core has presumedly four 128-bit ASIMD-pipelines. Each pipeline can presumedly do one 128- bit FMLA-instruction per cycle. This results in a theoretical peak performance of 102.4 FP32-GFLOPS or 51.2 FP64- GFLOPS for every Firestorm core. Additionally, M1 features one or more undocumented AMX-unit(s). The Firestorm AMX-unit can presumedly do one outer-product plus accumulate per cycle: 16x16x2=512 operations in FP32 or 8x8x2=128 operations in FP64. This results in a theoretical peak performance of 1638.4 FP32-GFLOPS or 409.6 FP64-GFLOPS when using the AMX-unit through the Firestorm cores

![graviton2_default](https://user-images.githubusercontent.com/1843685/142174351-d7af2dd3-79fb-4aff-936b-fc59412fdd78.png)
![altra_default](https://user-images.githubusercontent.com/1843685/142174374-cc8457dd-3cbc-4364-a45a-347954a07774.png)
![altra_memory](https://user-images.githubusercontent.com/1843685/142174419-bfdd6884-61ba-4b80-9631-749785a54b85.png)
![altra_m1_memory_compare](https://user-images.githubusercontent.com/1843685/142174452-b43deb82-9b2b-4b54-a174-1aed3972c8d2.png)
![a64fx_default](https://user-images.githubusercontent.com/1843685/142174470-b4317031-427e-47b5-97db-9ab38ae1415e.png)

---

Moving forward I'd propose:
* Assemble a table of specific samples/xgemm-configurations which are of interest to us
* Measure their performance on N1 and A64FX
* Collect ideas on issues and on how to get the kernels faster
* Get them fast :-)

**Comment by FreddieWitherden** [comment]
Apple M1, ARM N1, and A64FX; the good, the bad, and the ugly.  A secondary factor to include in the mix is the impact of strides.  If we look at the N1 performance for small matrices is very good.  However, if I bump lda and ldc then performance drops off far more so than on x86, even if the kernel itself has a relatively high computational intensity compared with memory bandwidth.

**Comment by breuera** [comment]
> If we look at the N1 performance for small matrices is very good.

Actually there's room for improvement for (very) small matrices on N1 (probably elsewhere too). That's mostly driven by unnecessary stack transfers (procedure call standard). We have this on the agenda over here; guess this is also the reason for the 5x5x5 performance in Fig. 14a of  https://dl.acm.org/doi/abs/10.1145/3458817.3476217

> A secondary factor to include in the mix is the impact of strides.

Makes sense.

**Comment by alheinecke** [comment]
Also for very small GEMMs the aarch64 GEMMs don't use "masking" so we may use more FMA than necessary. For the eltwise kernels partial loads have been developed https://github.com/hfp/libxsmm/blob/master/src/generator_common_aarch64.c#L88 and https://github.com/hfp/libxsmm/blob/master/src/generator_common_aarch64.c#L149. But they still have to be ported over to GEMM... I hope to do it over the coming holidays.

**Comment by breuera** [comment]
I started collecting a list of matrix-kernels of special interest by means of ``samples/xgemm``, i.e., M, N, K, lda, lbd, ldc, alpha, beta, precision, repetitions for EDGE:

> # time
>   20    9   35   35   35   35 1 0 SP   5000000
>   20    9    9   35    9   35 1 1 SP   10000000
>   20    6    3   35    3   35 1 1 SP   25000000
>   35    6    6   35    6   35 1 1 SP   20000000
> # volume
>   35    9   20   35   35   35 1 0 SP   5000000
>   35    9    9   35    9   35 1 1 SP   10000000
>   35    6    3   35    3   35 1 1 SP   20000000
> # surface
>   15    9   35   15   35   15 1 0 SP   5000000
>   15    9    9   15    9   15 1 0 SP   20000000
>   35    9   15   35   15   35 1 1 SP   10000000
>   15    6    9   15    9   15 1 1 SP   20000000
>   35    6   15   35   15   35 1 1 SP   10000000

Anything to add here?

---

In 8438ddd1d57e97f94848aeb55253c800a6ccc882 the A64FX-performance using SVE is as follows:

![a64fx_edge_8438ddd](https://user-images.githubusercontent.com/1843685/143311926-96ad6b17-b174-4bf9-a6ea-b13fd25117c9.png)

Also did have a look at 16 9 9 16  9 16 1 0 SP.
Biggest issue was A64FX having trouble with:
```
[...]
ld1rw	{z0.s}, p0/z, [x1]
add	x1, x1, #0x24
fmla	z23.s, p0/m, z1.s, z0.s
ld1rw	{z0.s}, p0/z, [x1]
add	x1, x1, #0x24
fmla	z24.s, p0/m, z1.s, z0.s
ld1rw	{z0.s}, p0/z, [x1]
[...]
```
One has to write it as:
```
[...]
add      x4, x1, 0x24*1
add      x5, x1, 0x24*2
add      x6, x1, 0x24*3
add      x7, x1, 0x24*4
add      x8, x1, 0x24*5
add      x9, x1, 0x24*6
add     x10, x1, 0x24*7
add     x11, x1, 0x24*8


ld1rw	{z0.s}, p0/z, [x1]
fmla	z23.s, p0/m, z1.s, z0.s
ld1rw	{z2.s}, p0/z, [x4]
fmla	z24.s, p0/m, z1.s, z2.s
ld1rw	{z3.s}, p0/z, [x5]
[...]
```
Quick and dirty fix in LIBXSMM:
![a64fx_edge_fix](https://user-images.githubusercontent.com/1843685/143312638-91412670-c305-4902-bfb4-dd8d3c73afa0.png)

**Comment by FreddieWitherden** [comment]
Out of interest how well do immediate offsets work?  `LD1RW` should support an immediate from 0 to 252 (7*0x24) and so all but one of the explicit add instructions can, on paper at least, be eliminated.  Also, is it the ordering of the adds away from the loads/fmla's which improves performance, or the use of separate registers (i.e., would an interleaved version of your second snippet perform the same?).

**Comment by alheinecke** [comment]
Just FYI #563 , it will not impact any backend work, but for EDGE and PyFR we will have to touch the codes.

**Comment by FreddieWitherden** [comment]
I think PyFR might be okay as it uses libxsmm_dfsspmdm_create and friends rather than calling the lower level functions directly.

**Comment by alheinecke** [comment]
Can we close this issue?

**Comment by FreddieWitherden** [comment]
So A64FX performance is still bad.  I am unsure what we want to do here.

**Comment by alheinecke** [comment]
Dropped the ball here, sorry. Yeah, A64FX has 11 (or so) cycles latency for FMAs. I'm afraid we right now cannot support this (time wise and hardware-wise). We did tons of fixed for V2 and N2 (and continue to improve here).
