### ISSUE TITLE
New & mateltwise-aligned GEMM frontend

### ISSUE THREAD

**Issue by alheinecke** [libxsmm/libxsmm#563]
The current GEMM frontend dates back to 2015/2016 prior to dates of mix-precision linear algebra as it used heavily in DL/AI in these days. Due to that mateltwise kernels (which have been developed in 2021) use a simple and quasi 100% ABI independent frontend. However, the GEMM frontend was patched over the last 6 years with more and more duct tape and is therefore very verbose. 

To fix this I have started reworking the entire GEMM frontend here: https://github.com/hfp/libxsmm/tree/new_gemm_frontend

A mock up frontend is already committed and over the next couple of days more details and implementations will follow:
https://github.com/hfp/libxsmm/blob/new_gemm_frontend/include/libxsmm_typedefs.h#L672
	Matelwise will have to use this as well, and then we rename to libxsmm_matrix_arg, the 4th arg is needed for prefetch pointers

We might keep the “clean” GEMMs:
https://github.com/hfp/libxsmm/blob/new_gemm_frontend/include/libxsmm_typedefs.h#L759
to 
 https://github.com/hfp/libxsmm/blob/new_gemm_frontend/include/libxsmm_typedefs.h#L773
(I’m also tempted to only keep F32 and F64 due to HPC codes for now and then even getting rid of those in version 2.0, however that would mean fixing all the EDGE / PyFR kernesl… but that’s not that hard, just typing… getting rid of 759-773 as well would make the backend cleaner and we would have a nice and unified frontend for mateltwise and GEMM).

For prefetch, alpha/beta, batch reduce:
https://github.com/hfp/libxsmm/blob/new_gemm_frontend/include/libxsmm_typedefs.h#L776
op, arges: 1st: brcount, 2nd: alpha, 3rd: beta (yes we can now support fully, runtime defined alpha/beta 😊)
4th point in matrix args will carry the prefetch address
2nd and 3rd points in matrix args will be used for quantization business…

Fused GEMM as discussed in the TPP slides:
https://github.com/hfp/libxsmm/blob/new_gemm_frontend/include/libxsmm_typedefs.h#L783
(not sure if we need more than d,e in any of our deep learning codes, we should double check this.

Everything from line:
https://github.com/hfp/libxsmm/blob/new_gemm_frontend/include/libxsmm_typedefs.h#L799
to
https://github.com/hfp/libxsmm/blob/new_gemm_frontend/include/libxsmm_typedefs.h#L841
will be removed.

Again… right now the whole thing is not functional, all what the commit did was adding the definitions and the fixing the code base to remove the prefetch pointers… all touched places are mare with “@TODO fix prefetch”.

I guess before merging this branch, we want to make a 1.7 release and announce that the next one is 2.0 and it will have incompatible API changes (and 2.0 removes all libxsmm_dnn domain potentially as well as we are now focusing on TPPs).

I will update this issue when there more & significant commits to https://github.com/hfp/libxsmm/tree/new_gemm_frontend

**Comment by alheinecke** [comment]
The new frontend is now live in master:
https://github.com/hfp/libxsmm/commit/cdb895a3cbd38b414f5420617be46132fa082155
While the old frontend still works:
@FreddieWitherden @breuera : please let me know if you have questions.
We are right now trying to figure out how to efficiently patch the entire code as we have to do a transformation of:
Old:
var = my_func_ABX_XYZ( foo, bar, foo2, bar2 );
New:
my_struct_1 struct_1;
my_struct_2 struct_2;
struct_1.field1 = A; struct_1.field2 = B;
struct_1.field3 = C; struct_1.field4 = foo;
struct_1.field5 = bar;
struct_2.field1 = foo2; struct_2.field2 = bar2;
var = my_new_func( struct_1, struct_2 );

**Comment by FreddieWitherden** [comment]
> The new frontend is now live in master:
> 
> https://github.com/hfp/libxsmm/commit/cdb895a3cbd38b414f5420617be46132fa082155
> 
> While the old frontend still works:
> 
> @FreddieWitherden @breuera : please let me know if you have questions.

Do any of the function calls in fsspmdm need updating at all?

Regards, Freddie.

**Comment by alheinecke** [comment]
Only if you plan to use prefetch and we will need to patch https://github.com/hfp/libxsmm/blob/master/src/libxsmm_fsspmdm.c#L209 to the v2 dispatch interface.

Prefetch support is only available through the weakly typed dispatch from now on:
https://github.com/hfp/libxsmm/blob/master/include/libxsmm.h#L131
https://github.com/hfp/libxsmm/blob/master/include/libxsmm_typedefs.h#L846

The same is true for low precision kernels, only F32 and F64 without prefetch will maintain a 3 arg kernel call:
https://github.com/hfp/libxsmm/blob/master/include/libxsmm_typedefs.h#L767
https://github.com/hfp/libxsmm/blob/master/include/libxsmm_typedefs.h#L769
(everything 770 and below is deprecated).
For low precision and prefetching the new "gemm" function is required:
https://github.com/hfp/libxsmm/blob/master/include/libxsmm_typedefs.h#L846

In general it would make sense to change all everything to the weakly typed interface, but for now we plan to keep:
https://github.com/hfp/libxsmm/blob/master/include/libxsmm_typedefs.h#L767
https://github.com/hfp/libxsmm/blob/master/include/libxsmm_typedefs.h#L769
(and only those).

**Comment by breuera** [comment]
Thanks, @alheinecke!

I got two simple ones:
1. Are these a frontend-facing changes only, i.e., anything to be aware of when touching the code-generation?
2. Porting for dummies: Have a look at https://github.com/hfp/libxsmm/blob/master/samples/xgemm/kernel.c#L504 and adapt our old calls accordingly? 😄

**Comment by alheinecke** [comment]
Re 1. Nothing changed, except that we JIT a handful of instructions to read the A,B,C and prefetch ptr from a struct. This needs to be ported over to sparse * 3D Tensor, 3D Tensor * sparse, dense * 3D tensor and 3D tensor * sparse and the sparse reg routine if prefetching is needed as there is no longer the variadic function call for the kernel. But the code here is trivial: https://github.com/hfp/libxsmm/blob/master/src/generator_gemm_sse_avx_avx2_avx512.c#L174 and the aarch64 gemm kernel has the aarch64 counter part. That also helps with Windows and Chrome OS support as we only have 1 arg in the calling convention. 

Re 2: yes for porting calls to the small GEMM kernel:
https://github.com/hfp/libxsmm/blob/master/samples/xgemm/kernel.c#L504  is the new dispatch call
https://github.com/hfp/libxsmm/blob/master/samples/xgemm/kernel.c#L542 is the new invoke call of the kernel and here you see the point from above, we are setting up a struct and then pass a pointer to that struct (single arg from OS calling convention PoV).

**Comment by alheinecke** [comment]
@FreddieWitherden : can you please give the branch hpc_spmat_3d_new_abi as test drive? It's using internally the new abi and this would allow us to cover prefetching and has support for Windows (you don't care I guess...)

@breuera : this branch has also the new API for the EDGE kernels, this can be already inspected (and they pass unit tests) in samples/edge
