### ISSUE TITLE
LIBXSMM_VLA_DECL / LIBXSMM_VLA_ACCESS weakly typed

### ISSUE THREAD

**Issue by alheinecke** [libxsmm/libxsmm#574]
With the latest and refactored GEMM / eltwise / equation API (v2) LIBXSMM's TPPs are completely weakly typed. However, right now it's not possible to write weakly typed TPP algorithms as LIBXSMM_VAL_* is strongly typed. 

Proposal: Introducing LIBXSMM_VLA_DECL_VOID/WEAK/WPTR/XYZ and LIBXSMM_VLA_ADDR_XYZ ( XYZ and other names: I'm failing to find something which clearly shows it's weakly typed and one gets a void ptr back). That means LIBXSMM_VLA_DECL_XYZ gets a libxsmm_datatype as type (defines a void*) and  LIBXSMM_VLA_ADDR_XYZ returns a void* to the address which is being accessed in the multi-dimenionsal field.

**Comment by alheinecke** [comment]
I have seen commit b805d8b15d193d39ed706e0c43d98ac44806390b, can we also have an ACCESS which takes typesize (8,4,2,1) instead of typename (short, int, etc.)

**Comment by hfp** [comment]
Yes, you will get it like `ACCESS_RAW` taking the typesize and returning `void*`.

**Comment by alheinecke** [comment]
Since we are using already ACCESS_RAW is there something more needed (from my side we can close this issue)

**Comment by hfp** [comment]
Resolved.
