### ISSUE TITLE
Should we keep the EDGE reproducer

### ISSUE THREAD

**Issue by alheinecke** [libxsmm/libxsmm#580]
@breuera Is this code being maintained/useful: https://github.com/libxsmm/libxsmm/tree/master/samples/edge/repro ? I haven't ported it over to the new frontend (#563) and I'm wondering if it makes sense to do so?

**Comment by breuera** [comment]
The reproducer is rather dated and currently not up-to-date with the solver.
I'd suggest to delete it and declutter LIBXSMM; we can revisit this later if needed.

**Comment by alheinecke** [comment]
Thanks, removed.
