### ISSUE TITLE
Can no longer compile branch aarch64-eltwise on Isambard (A64FX)

### ISSUE THREAD

**Issue by AntonioNoack** [libxsmm/libxsmm#585]
With the latest commits into aarch64_eltwise, I can no longer compile LIBXSMM.

There are two issues:

## First Issue

SYS_arch_prctl is unknown. It is used in `int libxsmm_cpuid_x86_amx_enable()` in *libxsmm_cpuid_x86.c*, and seems to be a specific syscall. (maybe `SYS_prctl` is equivalent??? That one is recommended by the compiler)

A solution that works for me, is to wrap this function in `#if defined(LIBXSMM_PLATFORM_X86) ... #endif`, but it might break stuff elsewhere.

## Second Issue

In the newly added test "eltwise_unary_gatter_scatter.c", `<immintrin.h>` is included. This header seems to be missing from A64FX, and again, my pseudo-solution was to wrap it inside a predefine, that disables it for me.

**Comment by AntonioNoack** [comment]
Addition to the second issue: when I remove this include, it compiles just fine, so maybe this include isn't even required in that file.

**Comment by alheinecke** [comment]
please submit a PR to master with the two fixes:
first issue: yes wrap the whole thing with #if defined(LIBXSMM_PLATFORM_X86) ... #endif  this is about enabling OS XSAVE state for for Intel AMX it compiles in our CI for ARM, Perhaps Isambard is different, however, as we will never go there, we can easily wrap it.

Second Issue: this is the incl. for x86 intriniscs and it's not needed, just an oversight, can be simply removed.

**Comment by alheinecke** [comment]
I had to revert #587 , as it doesn't compile with various versions of ICC and I think I also saw one clang.
Tried to fix it, didn't work -> see
https://github.com/libxsmm/libxsmm/commit/ea069cae900e1c06c5630fdd3867f059caf26e61
https://github.com/libxsmm/libxsmm/commit/d18311f33a30d602761058076304939f6cf25c36
https://github.com/libxsmm/libxsmm/commit/77887066e2edf705536bd8a7f798355bd4eca399

E.g. these are errors I was seeing for icc 18.0.3:
eltwise_binary_simple.c(188): error: expected an expression
BENCHMARK_INIT()
^

eltwise_binary_simple.c(188): error: identifier "l_archIndex" is undefined
BENCHMARK_INIT()
^

eltwise_unary_dropout.c(217): error: expected an expression
BENCHMARK_INIT()
^

**Comment by alheinecke** [comment]
Please have a look on the changes I pushed over the weekend into the aarch64_eltwise base branch.

I suggest instead of 3 macros that aim at injecting code, let's have some 2 functions: a) benchmark unary, b) benchmark binary. There is no need to run correctness checks and by default the benchmarking should be switched off. With these functions (implemented in eltwise_common.h) we now need only a single line each of the tester file and every compiler should be happy.

**Comment by AntonioNoack** [comment]
About these functions, that you propose:
- would they check a single kernel type (+=1 or 1/x or x²), or multiples?
- would they still support performance comparisons between two architectures?

If they would be functions, that only takes a function pointer, and measures its performance, the architecture could not be switched, and therefore no direct speedup calculation could take place. This is why I split it into macros in the first place.

**Comment by alheinecke** [comment]
no correctness check. The functions get all the required information (param struct, type, flags, etc.) Then it can read the additional env variable and JIT for a different architecture. The JIT for the second arch is not coupled to the correctness tester. 

so something like:
benchmark_unary( func_ptr_unary, unary_param, unary_type, unary_flags );
should do the trick.

**Comment by alheinecke** [comment]
I guess we can close this one.
