### ISSUE TITLE
Encoding VBROADCASTS[SD] [yz]mm1, xmm2

### ISSUE THREAD

**Issue by FreddieWitherden** [libxsmm/libxsmm#600]
Within the x86 code generation routines how can one emit `VBROADCASTS[SD] [yz]mm1, xmm2` for broadcasting the first lane of `xmm2` to all of the lanes of `zmm1/ymm1`?  Going through the code I can only find the reg/mem case rather than the reg/reg case.

The application for this is in the `asparse_reg` code where the ability to emit such an instruction would enable me to save a register.  (As rather than needing 8/16 permutations for all possible broadcasts in the single/double precision scenario we could go down to 7/15, respectively with the first lane being handled by VBROADCAST[SD] rather than VPERMD.)

**Comment by alheinecke** [comment]
I think the encodings are there and we can just pipe them through the reg/reg encoder:
```
VEX.256.66.0F38.W0 19 /r
VBROADCASTSD ymm1, m64
```
vs.
```
VEX.256.66.0F38.W0 19 /r
VBROADCASTSD ymm1, xmm2
```
I guess this is what you are looking for?

**Comment by FreddieWitherden** [comment]
> I guess this is what you are looking for?

Yes, along with the reg/reg zmm version for broadcasting from the first lane into all lanes of a 512-bit register.

**Comment by alheinecke** [comment]
please check latest master and close the issue if serves your needs.

**Comment by FreddieWitherden** [comment]
Looks good, once #599 is resolved I will test more extensively.
