### ISSUE TITLE
typo in enabling AMX state in the OS

### ISSUE THREAD

**Issue by airMeng** [libxsmm/libxsmm#601]
```/* enable AMX state in the OS on SPR and later */``` in the [code](https://github.com/libxsmm/libxsmm/blob/907fdfb18d24353c072c6b85d57da3392fd68de4/src/libxsmm_cpuid_x86.c#L82) like the following:
```cpp
if (0 != status || !(bitmask & (1<18))) return -1;
```
should be 
```cpp
if (0 != status || !(bitmask & (1<<18))) return -1;
```

reference: [onednn enabling AMX](https://github.com/intel-innersource/libraries.performance.math.onednn/blob/adceda1c63d5fbeb2edf019c88fc27a48bee32cc/src/cpu/x64/cpu_isa_traits.cpp#L316)

**Comment by airMeng** [comment]
@hshen14 @kevinintel cc

**Comment by kevinintel** [comment]
1<18 and 1<<18, thanks hengyu

**Comment by alheinecke** [comment]
can you please submit a PR

**Comment by airMeng** [comment]
> can you please submit a PR

Hi @alheinecke  nice to have such quick response, opened a PR in https://github.com/libxsmm/libxsmm/pull/602

**Comment by airMeng** [comment]
close due to fixed
