### ISSUE TITLE
libxsmm_gemm_batch_omp  is not yet fully supported？

### ISSUE THREAD

**Issue by HWWH123** [libxsmm/libxsmm#642]
No problem occurs when I call libxsmm_sgemm_batch, libxsmm_dgemm_batch, but Segmentation fault occurs when the same input calls libxsmm_sgemm_batch_omp() and libxsmm_dgemm_batch_omp().

**Comment by hfp** [comment]
Thank you for pointing out! There are still pending cleanup and rework steps for our master revision. For highest compatibility, please rely on our latest official release (which is lacking all new developments). Though, somewhat newer but also left behind are our "dbcsr" branch, or the tags "1.eol", "1.libxsmm_dnn_rip", and "1.old_kernelapi_rip" (no support for the branch/tags).

**Comment by hfp** [comment]
I have ported all batched gemm flavors to the desired API 2.0. You can find a new test case here:
https://github.com/libxsmm/libxsmm/blob/master/tests/gemmbatch.c#L160
The test may also illustrate using new API 2.0.

Summary:
* The functions `libxsmm_gemm_batch` and `libxsmm_gemm_batch_omp` are kept as in LIBXSMM 1.x. The internal implementation slightly improved.
* The functions `libxsmm_gemm_xbatch` and `libxsmm_gemm_xbatch_omp` are meant to replace `libxsmm_dgemm_batch` and `libxsmm_sgemm_batch` as well as their "omp-flavors" (`libxsmm_dgemm_batch_omp` and `libxsmm_sgemm_batch_omp`). The advantage of the xbatch variants is a type-generic interface at the expense of some casts necessary when passing typed double-pointers aka double** or float**.

I wonder if you actually have multiple groups of homogeneous GEMMs like whether you actually need the "xbatch-flavour" or if the "batch-flavor" is sufficient.

As a general note: the xbatch-variants are mostly for convenience supporting an API like MKL's `dgemm_batch` (I believe this is meanwhile available in OpenBLAS as well). Internally, the xbatch-variants simply call the batch-variant for every group. For highest compatibility, LIBXSMM can replace `dgemm_batch` or `sgemm_batch` at link-time (either per wrap-method or ldpreload). If you have further questions let me know. Your input is very welcome!

**Comment by HWWH123** [comment]
I noticed that these API are not using a common interface specification. The current community already has an interface for batch_gemm. I am curious as to why libxsmm does not adopt this widely used interface, like ARMPL, BLIS and MKL. 

Abdelfattah, Ahmad, et al. "A set of batched basic linear algebra subprograms and LAPACK routines." ACM Transactions on Mathematical Software (TOMS) 47.3 (2021): 1-23.

**Comment by hfp** [comment]
LIBXSMM is striving for interfaces that are perhaps standard but also for functionality that is not (yet) covered anywhere else (though some of our contributors were involved bringing up and discussing the need for batched gemm which finally emerged in ?gemm_batch for BLAS/LAPACK).

Beside of above note (or focus), `libxsmm_gemm_groups` is almost the same interface like `dgemm_batch` except that our function takes `libxsmm_datatype iprec` and `libxsmm_datatype oprec`:

```c
void libxsmm_gemm_groups(
  libxsmm_datatype iprec, libxsmm_datatype oprec, const char transa_array[], const char transb_array[],
  const libxsmm_blasint m_array[], const libxsmm_blasint n_array[], const libxsmm_blasint k_array[],
  const void* alpha_array, const void* a_array[], const libxsmm_blasint lda_array[],
                           const void* b_array[], const libxsmm_blasint ldb_array[],
  const void* beta_array,        void* c_array[], const libxsmm_blasint ldc_array[],
  const libxsmm_blasint* group_count, const libxsmm_blasint group_size[]);```

Further (and as noted earlier), LIBXSMM has link-wrappers for `dgemm_batch` and `sgemm_batch` (see [here](https://libxsmm.readthedocs.io/libxsmm_mm/#call-wrapper)). If you want so, LIBXSMM literally provides `?gemm_batch` just like Intel MKL. From that perspective, `libxsmm_gemm_batch` is simply what's called inside of a loop implementing `?gemm_batch` plus that `libxsmm_gemm_batch` allows to perform batches described by arrays of indexes *or* by arrays of pointers (`?gemm_batch` is something that only takes arrays of pointers). In general, indexes are more common than pointers especially in Fortran applications. A prime example is CP2K Open Source Molecular Dynamics or the DBCSR Library in particular performing batches based on index sets extracted from structured data, i.e., `libxsmm_gemm_batch` can extract indexes using Byte-measured strides, .e.g., if you have an array of structures based on something like:

```c
struct mystruct {
  int begin_a, begin_b, begin_c;
};
```

and something like `a_data`, `b_data`, and `c_data` (where `begin_a` etc. point into), then `libxsmm_gemm_batch` can be used right away without data transformation of the input. On top of `libxsmm_gemm_batch`, `libxsmm_mmbatch` provides an interface that allows external threading or using a multicore parallelization library of your choice (not just OpenMP).

**Comment by hfp** [comment]
I am closing the issue. Please feel free to provide feedback on our above mentioned APIv2.0. I am currently considering another flavor of batched GEMM allowing heterogeneous GEMMs (let me know if this can be useful for you).

**Comment by hfp** [comment]
It seems we miss `gemm_batch_strided`.
