### ISSUE TITLE
Assembly is broken on ARM64:  error: invalid output constraint '=a' in asm

### ISSUE THREAD

**Issue by yurivict** [libxsmm/libxsmm#669]
```
./src/libxsmm_timer.c:107:3: error: invalid output constraint '=a' in asm
  LIBXSMM_TIMER_RDTSC(result);
  ^
./src/libxsmm_timer.c:49:39: note: expanded from macro 'LIBXSMM_TIMER_RDTSC'
      __asm__ __volatile__ ("rdtsc" : "=a"(CYCLE), "=d"(libxsmm_timer_rdtsc_hi_)); \
                                      ^
./src/libxsmm_timer.c:160:5: error: invalid output constraint '=a' in asm
    LIBXSMM_TIMER_RDTSC(result);
    ^
./src/libxsmm_timer.c:49:39: note: expanded from macro 'LIBXSMM_TIMER_RDTSC'
      __asm__ __volatile__ ("rdtsc" : "=a"(CYCLE), "=d"(libxsmm_timer_rdtsc_hi_)); \
                                      ^
2 errors generated.
```

Full log http://ampere3.nyi.freebsd.org/data/130arm64-default/cfc0b7a81f2e/logs/libxsmm-1.17.log (IPv6 URL).

Version: 1.17
FreeBSD 13.1

**Comment by hfp** [comment]
I recommend building and deploying LIBXSMM for ARM64 as soon as LIBXSMM 2.0 is released (there is no value in doing so for v1.x). As you noticed, LIBXSMM is sort of a JIT-assembler which means architectural support is not covered just by being able to (cross-)compile the library on that architecture.

Let me know if this issue can be closed.

**Comment by hfp** [comment]
Closing this issue because v1.x does bring value for ARM and our build infrastructure is supposed to avoid building LIBXSMM on ARM by default.
