### ISSUE TITLE
FPE in libxsmm_fsspmdm_create on Ryzen 9 (zen 2)

### ISSUE THREAD

**Issue by mlohry** [libxsmm/libxsmm#681]
Probably linked to issue #680 , this line:

https://github.com/libxsmm/libxsmm/blob/6bcd42f74980aa31bd6b568b2e8f27d2dd47a6dc/src/libxsmm_fsspmdm.c#L67

FPEs due to N_sparse1=0, presumably due to not correctly picking up the cpuid.

**Comment by FreddieWitherden** [comment]
Can you check what is being output here:

https://github.com/libxsmm/libxsmm/blob/6bcd42f74980aa31bd6b568b2e8f27d2dd47a6dc/src/libxsmm_fsspmdm.c#L46

**Comment by mlohry** [comment]
> Can you check what is being output here:
> 
> https://github.com/libxsmm/libxsmm/blob/6bcd42f74980aa31bd6b568b2e8f27d2dd47a6dc/src/libxsmm_fsspmdm.c#L46

vl: 0
libxsmm_target_archid: 0
libxsmm_cpuid_vlen(libxsmm_target_archid): 4
typesize: 8

**Comment by FreddieWitherden** [comment]
It looks as if the architecture is not being probed correctly.  This is likely a bug in libxsmm.  For the moment exporting `LIBXSMM_TARGET="avx2" ` will resolve it (this is what we also have to use on SVE systems as the cpuid code is still under development there).

**Comment by hfp** [comment]
@mlohry Is your case running in a somehow virtualized environment like QEMU or Virtualbox, etc.?

**Comment by mlohry** [comment]
> For the moment exporting `LIBXSMM_TARGET="avx2" ` will resolve it (this is what we also have to use on SVE systems as the cpuid code is still under development there).

I still get vl=0

> @mlohry Is your case running in a somehow virtualized environment like QEMU or Virtualbox, etc.?

No, bare metal ubuntu 20.04.

**Comment by hfp** [comment]
@mlohry Thank you for the report and your reply! I will take a look.

**Comment by hfp** [comment]
@mlohry Can you retry? I fixed two things:

* More defensive expression to ensure we never get this zero, which you ran into (round-up) like lower VLEN than data-width.
  * This fix would still leave your application potentially with sub-par performance.
* Ensure that CPUID is acquired (even if LIBXSMM is not explicitly initialized).

Note: these fixes has nothing to do with AMD or "Zen" or Intel or whatever, it's just we never ran our CPUID-check to properly acquire the applicable vector-width.

The problem indicates your application never calls `libxsmm_init` in some suitable/upfront location. We are committed to be fully correct with "lazy initialization". However, you may still want to call `libxsmm_init` when your application initializes.

**Comment by mlohry** [comment]
@hfp confirmed it works now, thanks! And no I wasn't using libxsmm_init.

Now if there's any possibility of getting fsspmdm working for column major I'll be even more in your debt :)

**Comment by hfp** [comment]
> getting fsspmdm working for column major

@FreddieWitherden @alheinecke any comment?

**Comment by hfp** [comment]
@mlohry No debt please, it is totally free "as is" and forever (the previous "forever" is not double-quoted to avoid philosophic issues ;-)

**Comment by mlohry** [comment]
@FreddieWitherden mentioned in an email that column major wouldn't really work for our purposes, although any improvement over the dense case would be a win for me.

**Comment by FreddieWitherden** [comment]
> @FreddieWitherden mentioned in an email that column major wouldn't really work for our purposes, although any improvement over the dense case would be a win for me.

You can try loading a patch of columns (8 or 16) and transposing them to a small (row-major) array allocated on the stack.  This will let you use the row-major fsspmdm code which will write its output to another stack allocated array.  Finally, you can untranspose to your desired output array.  libxsmm should have a transpose routine which does the job.  Can even try doing the transpose in-place which might help with cache pressure.

Saying this, performance will likely not be as good as a pure row-major approach since we now have to spend time doing transposes.

**Comment by mlohry** [comment]
Thanks, I'll give that a shot and let you know how it performs.

**Comment by hfp** [comment]
> LIBXSMM should have a transpose routine which does the job. Can even try doing the transpose in-place which might help with cache pressure.

Indeed we have `libxsmm_itrans`, `libxsmm_itrans_batch`, and `libxsmm_itrans_batch_omp`. For the out-of-place flavor ("otrans"), there are even more options like external threading runtime. It can be even worth doing otrans with own scratch memory in order to perform "inplace transposes".

**Comment by alheinecke** [comment]
if you want bare-metal transposes, this is a good starting pointer:
https://github.com/libxsmm/libxsmm/blob/master/samples/eltwise/eltwise_unary_transform.c

**Comment by hfp** [comment]
Let me close this issue. For future discussion, please consider a new report. Though, this discussion is already split between here and #581.
