### ISSUE TITLE
Linker error "mismatches non-TLS reference" when using header-only library

### ISSUE THREAD

**Issue by mlohry** [libxsmm/libxsmm#693]
This seems to be a very obscure linker error and google isn't helping and I'm wondering if you've encountered this. When I include libxsmm_source.h to do a header-only build, the compile works and creates a shared library `libmylib.so`. When linking this library to the executable, I get this message:

```
/bin/ld: error_message: TLS definition in ./_bin/libmylib.so section .tbss mismatches non-TLS reference in //usr/lib64/libgssapi_krb5.so.2
//usr/lib64/libgssapi_krb5.so.2: error adding symbols: Bad value
```

When I include libxsmm.h and link to the compiled library I have no such issue and linking happens as expected. Any idea?

**Comment by hfp** [comment]
Sounds nasty. Can you please share a recipe/reproducer? Alternatively (if you think it's quicker), you can send me a private message and we can arrange some access (either on my end or on your side).

**Comment by mlohry** [comment]
It is nasty, unfortunately it's tied into a very complex build system so a reproducer will be difficult. Just hoping someone had seen this before. Feel free to close.
