### ISSUE TITLE
Include GiMMiK code in fsspmdm tests and benchmarks

### ISSUE THREAD

**Issue by FreddieWitherden** [libxsmm/libxsmm#694]
It would be good for benchmarking purposes if we included some of the reference C code produced by GiMMiK in our tests/benchmarks for fsspmdm.  I've attached a suite of generated kernel for prisms/hexes (corresponding to the matrices we have in libxsmm), and a driver which shows how they can be called.

This will let us see if any kernels are underperforming.

[gimmik.zip](https://github.com/libxsmm/libxsmm/files/9461625/gimmik.zip)

**Comment by hfp** [comment]
This task is completed. The performance script was updated to merge Gimmik results into a common/final CSV-file (individual CSV-files are created as well).

**Comment by FreddieWitherden** [comment]
For the GiMMiK kernels it is sometimes necessary to explicitly tell the compiler to use 512-bit vectors when compiling for AVX512 (otherwise it will go with 256-bit) and, for some of the larger kernels, increase the maximum loop size that the compiler will vectorize.  Do we have a generic way of handling these kinds of cflags?

**Comment by hfp** [comment]
I will add a generic option like `make VMAX=1` which will issue `-qopt-zmm-usage=high`, `-mprefer-vector-width=512`, or `-mprefer-vector-width=256` depending on compiler and target ISA.
