### ISSUE TITLE
A64FX: 9fd0fac, eltwise

### ISSUE THREAD

**Issue by breuera** [libxsmm/libxsmm#702]
The eltwise tests on A64FX are failing for [9fd0fac](https://github.com/libxsmm/libxsmm/commit/9fd0face1d0f55f27acf10f86b0b995ab9c30260):

```
steps:
  - command:
      - make PLATFORM=1 JIT=1 WERROR=1 BLAS=0 -j
      - cd samples/eltwise/
      - make PLATFORM=1 JIT=1 WERROR=1 BLAS=0 -j
      - ./run_test_aarch64_sve.sh
      - cd ../..
    label: ":pipeline: eltwise"
    agents:
      isa: "sve512"
[...]
```

```
[...]
gcc -dynamic -o eltwise_unary_gather_scatter obj/eltwise_unary_gather_scatter-c.o -L/hkfs/home/project/hk-project-test-scalfsu/hgf_prd6221/buildkite/builds/ftp-a64n1/edge/libxsmm-sve512/lib ../../lib/libxsmm.a -L/hkfs/home/project/hk-project-test-scalfsu/hgf_prd6221/buildkite/builds/ftp-a64n1/edge/libxsmm-sve512/lib ../../lib/libxsmmnoblas.a  -Wl,--gc-sections -Wl,-z,relro,-z,now -Wl,--export-dynamic -Wl,--as-needed -lm -lrt -ldl -Wl,--no-as-needed -fopenmp -Wl,--as-needed -lstdc++ -Wl,--no-as-needed -pthread
--
  | gcc -dynamic -o eltwise_unary_transform obj/eltwise_unary_transform-c.o -L/hkfs/home/project/hk-project-test-scalfsu/hgf_prd6221/buildkite/builds/ftp-a64n1/edge/libxsmm-sve512/lib ../../lib/libxsmm.a -L/hkfs/home/project/hk-project-test-scalfsu/hgf_prd6221/buildkite/builds/ftp-a64n1/edge/libxsmm-sve512/lib ../../lib/libxsmmnoblas.a  -Wl,--gc-sections -Wl,-z,relro,-z,now -Wl,--export-dynamic -Wl,--as-needed -lm -lrt -ldl -Wl,--no-as-needed -fopenmp -Wl,--as-needed -lstdc++ -Wl,--no-as-needed -pthread
  | Execute PIPELINE-ELTWISE with NTASKS=62, NPROCS=48, and OMP_NUM_THREADS=1
  | -> ERROR[255]: unary_xor_eqld
  | -> ERROR[132]: binary_mul_gtld
  | -> ERROR[132]: unary_dropout_eqld_65
  | -> ERROR[132]: binary_mul_eqld
  | -> ERROR[132]: binary_div_eqld
  | -> ERROR[132]: binary_add_eqld
  | -> ERROR[132]: unary_relu_gtld
  | -> ERROR[132]: unary_relu_eqld
  | -> ERROR[132]: binary_sub_gtld
  | -> ERROR[132]: binary_add_gtld
  | -> ERROR[255]: unary_xor_gtld
  | -> ERROR[132]: binary_sub_eqld
  | -> ERROR[132]: unary_copy_gtld
  | -> ERROR[132]: binary_div_gtld
  | -> ERROR[132]: unary_gelu_inv_eqld
  | -> ERROR[132]: unary_gelu_eqld
  | -> ERROR[132]: unary_tanh_inv_eqld
  | -> ERROR[132]: unary_tanh_eqld
  | -> ERROR[132]: unary_gelu_gtld
  | -> ERROR[132]: unary_tanh_gtld
  | -> ERROR[132]: unary_sigmoid_eqld
  | -> ERROR[132]: unary_gelu_inv_gtld
  | -> ERROR[132]: unary_tanh_inv_gtld
  | -> ERROR[132]: binary_muladd_eqld
  | -> ERROR[132]: binary_muladd_gtld
  | -> ERROR[132]: unary_sigmoid_gtld
  | -> ERROR[132]: unary_sigmoid_inv_eqld
  | -> ERROR[132]: unary_sigmoid_inv_gtld
  | -> ERROR[132]: unary_sqrt_gtld
  | -> ERROR[132]: unary_dropout_gtld_65
  | -> ERROR[132]: unary_negate_gtld
  | -> ERROR[132]: unary_rcp_sqrt_gtld
  | -> ERROR[132]: unary_rcp_gtld
  | -> ERROR[132]: unary_copy_eqld
  | -> ERROR[132]: unary_exp_gtld
  | -> ERROR[132]: unary_sqrt_eqld
  | -> ERROR[132]: unary_rcp_eqld
  | -> ERROR[132]: unary_x2_gtld
  | -> ERROR[132]: unary_inc_eqld
  | -> ERROR[132]: unary_rcp_sqrt_eqld
  | -> ERROR[132]: unary_exp_eqld
  | -> ERROR[132]: unary_inc_gtld
  | -> ERROR[132]: unary_x2_eqld
  | -> ERROR[132]: unary_negate_eqld
  | -> VALID[000]: unary_trans_64b_eqld
  | -> VALID[000]: unary_trans_64b_gtld
  | -> VALID[000]: unary_trans_32b_gtld
  | -> VALID[000]: unary_trans_32b_eqld
  | -> VALID[000]: unary_trans_08b_eqld
  | -> VALID[000]: unary_trans_08b_gtld
  | -> VALID[000]: unary_vnni_16b_gtld
  | -> VALID[000]: unary_trans_padm_mod2_16b_gtld
  | -> VALID[000]: unary_trans_padn_mod2_16b_eqld
  | -> VALID[000]: unary_trans_padn_mod2_16b_gtld
  | -> VALID[000]: unary_trans_padnm_mod2_16b_gtld
  | -> VALID[000]: unary_trans_padnm_mod2_16b_eqld
  | -> VALID[000]: unary_vnnitrans_16b_eqld
  | -> VALID[000]: unary_trans_padm_mod2_16b_eqld
  | -> VALID[000]: unary_vnnitrans_16b_gtld
  | -> VALID[000]: unary_vnni_16b_eqld
  | -> VALID[000]: unary_trans_16b_eqld
  | -> VALID[000]: unary_trans_16b_gtld
  | --------------------------------------------------------------------------------
  | 🚨 Error: The command exited with status 123
  | user command error: exit status 123
```

**Comment by hfp** [comment]
I am on it.

**Comment by hfp** [comment]
b397a5489b55656a7f7cca3e290965b00a6f6113 passes four our non-SVE tests. So I guess this is A64FX/SVE specific.

**Comment by alheinecke** [comment]
@egeor there might be something broken with SVE after the AVX2 bf16/fp16 merge

**Comment by egeor** [comment]
The only thing this merge really did wrt non-x86 is sth like the following:
https://github.com/libxsmm/libxsmm/blob/main/samples/eltwise/kernel_test/binary_div_eqld.sh#L5

I assume all these would have to be enhanced with a condiiton like:
${LIBXSMM_TARGET} == "aarch64" || "sve"

**Comment by egeor** [comment]
or make the default only f32 and add the enhanced precisions for avx2 or so

**Comment by alheinecke** [comment]
In fact SVE256 supports BF16, correct? So what would be the correct condition?

**Comment by egeor** [comment]
sve256 for sure does, the correct for that would be add a similar if for the sve256 arch and the correct precision string

**Comment by alheinecke** [comment]
Can you please provide the bash if which is needed than we can use sed to patch it

**Comment by egeor** [comment]
For simple unary:

if [ [ ${LIBXSMM_TARGET} == "aarch64" ] ||  [${LIBXSMM_TARGET} == "sve512" ]] ; then
    PREC_LIST="F32_F32_F32";
fi

if [[ ${LIBXSMM_TARGET} == "neov1" ]]; then
    PREC_LIST="F32_F32_F32 BF16_BF16_F32 F32_BF16_F32 BF16_F32_F32";
fi

For unary copy:

if [ [ ${LIBXSMM_TARGET} == "aarch64" ] ||  [${LIBXSMM_TARGET} == "sve512" ]] ; then
    PREC_LIST="F32_F32_F32";
fi

if [[ ${LIBXSMM_TARGET} == "neov1" ]]; then
    PREC_LIST="F32_F32_F32 BF16_BF16_BF16 BF16_BF16_F32 F32_BF16_F32 BF16_F32_F32";
fi

For reduce:

if [ [ ${LIBXSMM_TARGET} == "aarch64" ] ||  [${LIBXSMM_TARGET} == "sve512" ]] ; then
    PREC_LIST="F32";
fi

if [[ ${LIBXSMM_TARGET} == "neov1" ]]; then
    PREC_LIST="F32 BF16";
fi

For binary:

if [ [ ${LIBXSMM_TARGET} == "aarch64" ] ||  [${LIBXSMM_TARGET} == "sve512" ]] ; then
    PREC_LIST="F32_F32_F32_F32";
fi

if [[ ${LIBXSMM_TARGET} == "neov1" ]]; then
    PREC_LIST="F32_F32_F32_F32 F32_F32_BF16_F32 F32_BF16_F32_F32 F32_BF16_BF16_F32 BF16_F32_F32_F32 BF16_F32_BF16_F32 BF16_BF16_F32_F32 BF16_BF16_BF16_F32";
fi

**Comment by alheinecke** [comment]
Thanks.

So I guess we can just use default F32 only as you mentioned before. However, I have one question on the neov1 if, shouldn't that be:

`if [ [ ${LIBXSMM_TARGET} == "neov1" ] || [ ${LIBXSMM_TARGET} == "sve256" ] ]; then`

or are we not sure that ifs are all correct in the code?

**Comment by alheinecke** [comment]
So the only arch which checks internally for BF15 is neov1, correct?

Then all the others ARM archs should be covered like this, correct?

For simple unary (as example, need to adjust all others as well):
```
if [ [ ${LIBXSMM_TARGET} == "arm" ] ||
     [ ${LIBXSMM_TARGET} == "arm64" ] ||
     [ ${LIBXSMM_TARGET} == "arm_v81" ] ||
     [ ${LIBXSMM_TARGET} == "arm_v82" ] ||
     [ ${LIBXSMM_TARGET} == "appl_m1" ] ||
     [ ${LIBXSMM_TARGET} == "sve256" ] ||
     [ ${LIBXSMM_TARGET} == "a64fx" ] ||
     [ ${LIBXSMM_TARGET} == "aarch64" ] || 
     [ ${LIBXSMM_TARGET} == "sve512" ] ] ; then
    PREC_LIST="F32_F32_F32";
fi

```

However, as you suggest it might be cleaner to set F32 as default and then have a clean if for "hsw" and "adl".

**Comment by egeor** [comment]
Yes the above should work for our CI (yet soon it will have to change again as I will submit an F64 PR)

**Comment by alheinecke** [comment]
Then I suggest fixing this with this PR, as I assume that will happen withing the next couple of days, am I right? 

Let's then rework the ifs (put avx512/avx512_vl under one and add one for hsw or adl)

In fact we should look into a wrapper script "arch_setup_precs_unary.sh" and in the actual tester we can do 
`source arch_setup_precs_unary.sh `
Then in future it's only one place which needs changes.

**Comment by egeor** [comment]
Sounds like a plan. Should have a draft FP64 PR by Friday and potentially such an arch_setup_precs_*.sh by early next week.

**Comment by breuera** [comment]
The tests are passing again since [f3bf9e8](https://github.com/libxsmm/libxsmm/commit/f3bf9e83d09ce5f756967227f599fc334baeebd9).
Closing this issue.
