### ISSUE TITLE
Warnings when building libxsmm with clang 14 from inside the tpp-sandbox

### ISSUE THREAD

**Issue by rengolin** [libxsmm/libxsmm#704]
```
  0% [0:1/2] 0.0/s, 0.004s Re-checking globbed directories...
  9% [15:24/163] 24.8/s, 0.606s Building C object CMakeFiles/xsmm.dir/_deps/xsmm-src/src/generator_gemm_common.c.o
/home/rengolin/devel/intel/tpp-sandbox/build/_deps/xsmm-src/src/generator_gemm_common.c:1216:5: warning: default label in switch which covers all enumeration values [-Wcovered-switch-default]
    default:
    ^
1 warning generated.
```
```
 42% [69:78/163] 29.1/s, 2.373s Building C object CMakeFiles/xsmm.dir/_deps/xsmm-src/src/generator_x86_instructions.c.o
/home/rengolin/devel/intel/tpp-sandbox/build/_deps/xsmm-src/src/generator_x86_instructions.c:3806:7: warning: unannotated fall-through between switch labels [-Wimplicit-fallthrough]
      default:
      ^
/home/rengolin/devel/intel/tpp-sandbox/build/_deps/xsmm-src/src/generator_x86_instructions.c:3806:7: note: insert 'break;' to avoid fall-through
      default:
      ^
      break; 
1 warning generated.
```
```
 51% [84:93/163] 30.0/s, 2.796s Building C object CMakeFiles/xsmm.dir/_deps/xsmm-src/src/libxsmm_main.c.o
/home/rengolin/devel/intel/tpp-sandbox/build/_deps/xsmm-src/src/libxsmm_main.c:2248:5: warning: default label in switch which covers all enumeration values [-Wcovered-switch-default]
    default: { /* unknown kind */
    ^
1 warning generated.
```

**Comment by hfp** [comment]
Can you let me know how you CMake configure step looks like if it was any special? I guess `-Weverything` stems from some CMake configure option I am missing.

**Comment by hfp** [comment]
> I don't have any special flags on TPP's build CMake, just the bare minimum.

The thing is, I cannot reproduce the issue. The idea is to improve our code analysis and flags to avoid this issue on our side (also in the future). Otherwise, just to get rid of the warning is not a problem.

**Comment by rengolin** [comment]
Did you build just libxsmm or did you try to build it from the sandbox?

This is what I'm using:
```
$ clang --version
clang version 14.0.6
```

CMake:
```
cmake -G Ninja \
      -DCMAKE_C_COMPILER=clang \
      -DCMAKE_CXX_COMPILER=clang++ \
      -DMLIR_DIR=.../llvm-build/lib/cmake/mlir \
      -DLLVM_EXTERNAL_LIT=.../llvm-build/bin/llvm-lit
```

**Comment by hfp** [comment]
I updated LIBXSMM as fetched by the TPP-sandbox build. These warning were not related to the fetched version/SHA of LIBXSMM but present in general for LIBXSMM's code-base, i.e., when `LIBXSMMROOT` is present for our TPP-work.

Also, `-Weverything` (which is not recommended for general use and specific to Clang), LIBXSMM already checked with `-Wall -Wextra -pedantic` and some more flags.

I still wonder why even our CI for the TPP-sandbox aka TPP-compiler never pointed out these warnings (given we use Clang 14.0.6 as well). Though, [your](https://github.com/libxsmm/libxsmm/issues/704#issuecomment-1316884864) settings are really not special and likewise our CI configure step. Anyhow, the issue should be resolved now.

**Comment by hfp** [comment]
Thank you for your report!
