### ISSUE TITLE
Fp16 / int8 support for sparse matrix multiplication?

### ISSUE THREAD

**Issue by CosimoRulli** [libxsmm/libxsmm#705]
Hello developers, 
thank you for the amazing work you made with this library. I was wondering if you are planning to provide implementations for fp16/int8 sparse matrix multiplication. 

Best regards

**Comment by hfp** [comment]
Thank you for the kind words.

I wonder if your sparse MM can be amortized like a fixed matrix portrait or consecutive SpMM with the same sparsity structure? What is the format you have in mind, CSR/CSC, COO, or anything more fancy?

**Comment by CosimoRulli** [comment]
Sorry, I just realize that my question was quite broad actually. I'll try to explain myself. Consider a multiplication $A \cdot B = C$, where $A$ is a sparse matrix in the CSR format, and $B,C$ are dense matrices. Usually, non-zero entries in $A$ are stored as float32 values, and this holds also for $B$ and $C$. In my application, I can store the values in $A, B, C$ using int8/fp16. Hence, I can fit $2/4 \times$ the data in the same vector register and I would expect a proportional speedup in the computation. I think that this would entail to convert the broadcast and the fused-multiply add operations from float32 to float16/int8.

**Comment by alheinecke** [comment]
Which functions are using today with libxsmm? The only ones we are going to support in future are those used here:
https://github.com/libxsmm/libxsmm/tree/main/samples/deeplearning/sparse_weight_mult
When you need wider accumulation, you need need consecutive non-zeros, e.g. 4 for int8 such that one could use VNNI at full throughput (of course this ins only at kernel level, this can be achieved by permutation per-processing not part of libxsmm calls). 
FP16 is only supported with FP16 accumulation on 4th Gen Xeon (Sapphire Rapids), in this case the broadcasting of scalar FP16 (and therefore 100% unstructured sparsity works) in the FMA works as long as you have 32 pixels or minibatch. There is no client support as Intel client doesn't support AVX512. AMD's Zen4 AVX512 implementation doesn't support FP16.

**Comment by CosimoRulli** [comment]
Thank you for your detailed answer. I am referring to the functions used [here]([sparse_weight_A_mult.c](https://github.com/libxsmm/libxsmm/blob/main/samples/deeplearning/sparse_weight_mult/sparse_weight_A_mult.c). Is it possible to the same thing you described for fp16 but for int8 on Sapphire Rapids? Are you, by any chance, planning to release such routines?

**Comment by alheinecke** [comment]
No, it's not possible. int8 through VNNI on SPR (and CLX, CPX, ICX) is actually a 32bit instruction. It takes 4 int8 values packed and runs a small dot-product. While the code generation is trivial (it's literally issuing a VNNI instruction instead of an FP32 FMA, so a 1hr job) , it requires that 4 non-zero weights are now contiguous. As we haven't looked at what is required to make this work in terms of matrix permutations we haven't looked into this. If you have some information on such permutations and how one can run a topology fast end-to-end without extra reorders, it's very simply to add the code and experiencing up to 4x over FP32.

**Comment by hfp** [comment]
Thank you again for contributing and for your kind words!
