### ISSUE TITLE
eltwise_unary_reduce: validation fails for avx512_vl256

### ISSUE THREAD

**Issue by hfp** [libxsmm/libxsmm#715]
Here is how to build the code:

```bash
make SYM=2 -j
cd samples/eltwise
make SYM=2 -j
```

The following passes (avx512_vl256_clx):

```bash
LIBXSMM_TARGET=avx512_vl256_clx ./eltwise_unary_reduce 1 11 100 1 0 1 1 F64 0 0 0 0 0
```

However, avx512_vl256 fails validation:

```bash
LIBXSMM_TARGET=avx512_vl256 ./eltwise_unary_reduce 1 11 100 1 0 1 1 F64 0 0 0 0 0
```

The code for clx does `vpbroadcastq (%rsp),%ymm29` and `ymm29` is properly referred inside of the loop body. However, for the skx flavor, broadcast refers to `ymm13` but the loop still refers to `ymm29`.

**Comment by egeor** [comment]
Commit #5894e4f29a07dc45f7e867384fb89a824e2b9831 should fix this, let's wait for the CI

**Comment by hfp** [comment]
Fixed
