### ISSUE TITLE
SpMDM kernel in latest libxsmm

### ISSUE THREAD

**Issue by Z-Y00** [libxsmm/libxsmm#721]
Hi,
I found there has been a huge update in the new interface for SpMDM.

https://github.com/libxsmm/libxsmm/commit/68a9fca9d4d2d4cee5b67d99d3c218769b92c0dd

It seems the new libxsmm_dfsspmdm_create() require matrix A's memory location to be known when creating it.
Personally, I found this a little bit unconvenient for my use case, where the memory was managed by a ML engine.
I can only get the matrix's address when the operator is executed. 
So maybe calling libxsmm_dfsspmdm_create() every time the engine executes SpMDM would introduce much overhead.
I'm wondering if there is any workaround or I should switch to older version of SpMDM implementation.
Thank you!

**Comment by alheinecke** [comment]
SpMDM has been removed from libxsmm as this code was dropped from Tensorflow. 

The new codes are:
fsspmdm: here the "A" matrix is const and hold in registers, hence the matrix needs to be known at JIT time (the code is JITed targetting pattern and values)
packed_gemm (https://github.com/libxsmm/libxsmm/tree/main/samples/deeplearning/sparse_weight_mult) : here we need special layouts and only the sparsity pattern needs to be known as the code is JITed only according to the pattern, but not the values. This feature (for now) is experimental. If not used carefully, the kernels can grow and exceed the code size of 128KB. In this case the matrix has to be decomposed into several blocks, and this is the user's responsibility at this point.

**Comment by hfp** [comment]
Thank you for your contribution! Feel free to ask more questions opening a new issue.
