### ISSUE TITLE
Direct Sparse Convolution

### ISSUE THREAD

**Issue by Z-Y00** [libxsmm/libxsmm#722]
Hi,
It was mentioned in the readme that:

LIBXSMM's SPMDM domain (SParseMatrix-DenseMatrix multiplication) evolved from SkimCaffe, and since then LIBXSMM implements the sparse operations in SkimCaffe.

I'm wondering if libxsmm also support the direct sparse convolution used in SkimCaffe, as in SkimCaffe's code: caffe::ConvolutionParameter_ConvMode_DIRECT_SCONV.
I couldn't find the option in the source code libxsmm.

**Comment by alheinecke** [comment]
Let me remove this references from the read. With the retirement of SpMDM, we missed this one.

**Comment by Z-Y00** [comment]
Thanks for the information. 
I'm wondering if I want to test Direct Sparse Convolution, is there any older version of libxsmm I can try?

**Comment by alheinecke** [comment]
no, we never implemented. The only direct sparse convolution we have is here: https://github.com/libxsmm/libxsmm/blob/main/samples/deeplearning/sparse_weight_mult/parallel_sparse_weight_B_conv.c

**Comment by Z-Y00** [comment]
Thank you for the clarification!

**Comment by Z-Y00** [comment]
Happy new year! 
I'm wondering about the reason Direct Sparse Convolution was never implemented.
Was it due to worse performance compared with other sparse algorithms?
Thank you!

**Comment by alheinecke** [comment]
because of interest in the community and that we separated compound operations (such as convolutions) out of  libxsmm. The pointer above is using libxsmm basic functions.
