### ISSUE TITLE
Missing erroring out for bf16 compute relu on neov1 arch

### ISSUE THREAD

**Issue by kvoronin-intel** [libxsmm/libxsmm#726]
Currently, having an unary TPP for RELU with **bf16 as compute datatype** (and bf16 input/output datatypes) is not supported on neov1 and produces wrong masks (don't remember if the primary output was valid).

While it can be low priority to implement this case, we should at least **produce meaningful errors**, both for standalone relu TPPs as well as for equivalent nodes in the equations.

E.g., such a TPP is used in batchnorm fwd equation on x86 and currently uses an fp32 compute relu as a workaround. 

A reproducer is not available right now but the issue is known so hopefully this is enough information.

**Comment by egeor** [comment]
Commit 8eec24c267faf1831a82a2d1fadec15d09ba3733 adresses this.
