### ISSUE TITLE
Jitting equation with LIBXSMM built with DBG=1 triggers assertion failure sporadically

### ISSUE THREAD

**Issue by kvoronin-intel** [libxsmm/libxsmm#727]
Note: Originally issue has been seen on x86 but at the moment of opening the issue it only reproduces on arm, neov1 (gvt3).

Error:
`
python: ./src/generator_matequation_regblocks_aarch64.c:203: libxsmm_generator_mateqn_adjust_args_addr_aarch64: Assertion `(0) && *"Invalid datatype"' failed.
 (on x86 it failed in the equivalent place
python: ./src/generator_matequation_regblocks_avx_avx512.c:264: libxsmm_generator_mateqn_adjust_args_addr: Assertion `(0) && *"Invalid datatype"' failed.
)
`

Equation:
Schematic of the expression tree (Pre-order)
BINARY: 1 0 (timestamp = 3, tmp = 1)
|---UNARY: 18 16 (timestamp = 2, tmp = 1)
    |---BINARY: 2 0 (timestamp = 1, tmp = 1)
        |---TERNARY: 1 560 (timestamp = 0, tmp = 0)
            |---ARG: 32 7 32 0 -41872
            |---ARG: 32 1 1 1 -41872
            |---ARG: 32 1 1 2 -41872
        |---ARG: 32 7 32 3 -41872
|---ARG: 32 1 1 4 -41872

which is the first equation of bwd_w (backward by weight) pass of the batchnorm.

After adding a printf around the failed line in libxsmm
`
printf("dbg libxsmm: arg_info[%d].dtype = %d i_adjust_type = %d (%d and %d are of interest) arg_info[%d].bcast_type = %d\n",
          i, arg_info[i].dtype, i_adjust_type, M_ADJUSTMENT, N_ADJUSTMENT, i, arg_info[i].bcast_type);
`
I see:
dbg libxsmm: arg_info[0].dtype = 2 i_adjust_type = 1 (0 and 1 are of interest) arg_info[0].bcast_type = 0
dbg libxsmm: arg_info[1].dtype = 1 i_adjust_type = 1 (0 and 1 are of interest) arg_info[1].bcast_type = 2
dbg libxsmm: arg_info[2].dtype = 1 i_adjust_type = 1 (0 and 1 are of interest) arg_info[2].bcast_type = 2
dbg libxsmm: arg_info[3].dtype = 2 i_adjust_type = 1 (0 and 1 are of interest) arg_info[3].bcast_type = 0
dbg libxsmm: arg_info[4].dtype = **1869835329** i_adjust_type = 1 (0 and 1 are of interest) arg_info[4].bcast_type = **1886745376**

(on x86 I observed dtype = 0 which also leads to a failure, it was sporadic but very often)

**For a good (no failures) run on x86 the log will say:**
Schematic of the expression tree (Pre-order)
BINARY: 1 0 (timestamp = 3, tmp = 1)
|---UNARY: 18 16 (timestamp = 2, tmp = 1)
    |---BINARY: 2 0 (timestamp = 1, tmp = 1)
        |---TERNARY: 1 560 (timestamp = 0, tmp = 0)
            |---ARG: 32 7 32 0 -2071456714
            |---ARG: 32 1 1 1 -2071456714
            |---ARG: 32 1 1 2 -2071456714
        |---ARG: 32 7 32 3 -2071456714
|---ARG: 32 1 1 4 -2071456714

HP calculator (RPN) print of the expression tree (Post-order)
ARG ARG ARG TERNARY-1 ARG BINARY-2 UNARY-18 ARG BINARY-1.
`
dbg libxsmm: arg_info[0].dtype = 2 i_adjust_type = 1 (0 and 1 are of interest) arg_info[0].bcast_type = 0
dbg libxsmm: arg_info[1].dtype = 1 i_adjust_type = 1 (0 and 1 are of interest) arg_info[1].bcast_type = 2
dbg libxsmm: arg_info[2].dtype = 1 i_adjust_type = 1 (0 and 1 are of interest) arg_info[2].bcast_type = 2
dbg libxsmm: arg_info[3].dtype = 2 i_adjust_type = 1 (0 and 1 are of interest) arg_info[3].bcast_type = 0
dbg libxsmm: arg_info[4].dtype = 0 i_adjust_type = 1 (0 and 1 are of interest) arg_info[4].bcast_type = 0
dbg libxsmm: arg_info[0].dtype = 2 i_adjust_type = 1 (0 and 1 are of interest) arg_info[0].bcast_type = 0
dbg libxsmm: arg_info[1].dtype = 1 i_adjust_type = 1 (0 and 1 are of interest) arg_info[1].bcast_type = 2
dbg libxsmm: arg_info[2].dtype = 1 i_adjust_type = 1 (0 and 1 are of interest) arg_info[2].bcast_type = 2
dbg libxsmm: arg_info[3].dtype = 2 i_adjust_type = 1 (0 and 1 are of interest) arg_info[3].bcast_type = 0
dbg libxsmm: arg_info[4].dtype = 0 i_adjust_type = 1 (0 and 1 are of interest) arg_info[4].bcast_type = 0
`

Likely something remains uninitialized (and can be potentially unused) in the equations hence the issue.

**Comment by egeor** [comment]
Commit a8988e25b20ad7c6d274f077ddc29b25072b6943 should address this issue.

**Comment by kvoronin-intel** [comment]
Thanks, the fix looks good! The reproducer showed irregular behavior but I don't the issue anymore on x86 (can't check on ARM as it uses the non-merged branch with other fixes) and I think it is safe to close this issue.
