### ISSUE TITLE
Compute type bf16 does not return an error for a binary TPP (add with broadcast)

### ISSUE THREAD

**Issue by kvoronin-intel** [libxsmm/libxsmm#732]
Jitting a binary TPP (binary add) with BF16 compute type returns an erroneous kernel instead of an error [which should be a solution in my understanding].
Branch: main @ f07a39e3eac410a326262b9d8fefc506435efb27

Code snippet:
`
  libxsmm_meltwfunction_binary colbias_add_tpp;
  auto l_binary_shape = libxsmm_create_meltw_binary_shape(32, 7, 32, 32, 32, LIBXSMM_DATATYPE_BF16, LIBXSMM_DATATYPE_BF16, LIBXSMM_DATATYPE_BF16, LIBXSMM_DATATYPE_BF16);//LIBXSMM_DATATYPE_F32);
  colbias_add_tpp = libxsmm_dispatch_meltw_binary_v2( LIBXSMM_MELTW_TYPE_BINARY_ADD, l_binary_shape, LIBXSMM_MELTW_FLAG_BINARY_BCAST_COL_IN_1);
  if (colbias_add_tpp == NULL) {
    printf("kernel =  NULL\n");
    exit(-1);
  } else {
    printf("kernel jitted successfully\n");
    exit(0);
`

Result:
`
LIBXSMM-JIT-DUMP(ptr:file) 0x7f8f052dc000 : libxsmm_spr_tsize21622_32x7_32x32x32x0_opcode3_flags8_params1.meltw
kernel jitted successfully
`

Jitted code:
XDIS 0: DATAXFER  BASE       4C8B4720                 mov r8, qword ptr [rdi+0x20]
XDIS 4: DATAXFER  BASE       488B4740                 mov rax, qword ptr [rdi+0x40]
XDIS 8: DATAXFER  BASE       4C8B4F60                 mov r9, qword ptr [rdi+0x60]
XDIS c: DATAXFER  AVX512EVEX 62D1FF486F08             vmovdqu16 zmm1, zmmword ptr [r8]
XDIS 12: DATAXFER  AVX512EVEX 62D1FF486F5001           vmovdqu16 zmm2, zmmword ptr [r8+0x40]
XDIS 19: DATAXFER  AVX512EVEX 62D1FF486F5802           vmovdqu16 zmm3, zmmword ptr [r8+0x80]
XDIS 20: DATAXFER  AVX512EVEX 62D1FF486F6003           vmovdqu16 zmm4, zmmword ptr [r8+0xc0]
XDIS 27: DATAXFER  AVX512EVEX 62D1FF486F6804           vmovdqu16 zmm5, zmmword ptr [r8+0x100]
XDIS 2e: DATAXFER  AVX512EVEX 62D1FF486F7005           vmovdqu16 zmm6, zmmword ptr [r8+0x140]
XDIS 35: DATAXFER  AVX512EVEX 62D1FF486F7806           vmovdqu16 zmm7, zmmword ptr [r8+0x180]
XDIS 3c: DATAXFER  AVX512EVEX 62F1FF286F00             vmovdqu16 ymm0, ymmword ptr [rax]
XDIS 42: DATAXFER  AVX512EVEX 62F27D4823C0             vpmovsxwd zmm0, ymm0
XDIS 48: AVX512    AVX512EVEX 62F17D4872F010           vpslld zmm0, zmm0, 0x10
XDIS 4f: AVX512    AVX512EVEX 62F1F54858C8             vaddpd zmm1, zmm1, zmm0
XDIS 55: DATAXFER  AVX512EVEX 62F1FF286F00             vmovdqu16 ymm0, ymmword ptr [rax]
XDIS 5b: DATAXFER  AVX512EVEX 62F27D4823C0             vpmovsxwd zmm0, ymm0
XDIS 61: AVX512    AVX512EVEX 62F17D4872F010           vpslld zmm0, zmm0, 0x10
XDIS 68: AVX512    AVX512EVEX 62F1ED4858D0             vaddpd zmm2, zmm2, zmm0
XDIS 6e: DATAXFER  AVX512EVEX 62F1FF286F00             vmovdqu16 ymm0, ymmword ptr [rax]
XDIS 74: DATAXFER  AVX512EVEX 62F27D4823C0             vpmovsxwd zmm0, ymm0
XDIS 7a: AVX512    AVX512EVEX 62F17D4872F010           vpslld zmm0, zmm0, 0x10
XDIS 81: AVX512    AVX512EVEX 62F1E54858D8             vaddpd zmm3, zmm3, zmm0
XDIS 87: DATAXFER  AVX512EVEX 62F1FF286F00             vmovdqu16 ymm0, ymmword ptr [rax]
XDIS 8d: DATAXFER  AVX512EVEX 62F27D4823C0             vpmovsxwd zmm0, ymm0
XDIS 93: AVX512    AVX512EVEX 62F17D4872F010           vpslld zmm0, zmm0, 0x10
XDIS 9a: AVX512    AVX512EVEX 62F1DD4858E0             vaddpd zmm4, zmm4, zmm0
XDIS a0: DATAXFER  AVX512EVEX 62F1FF286F00             vmovdqu16 ymm0, ymmword ptr [rax]
XDIS a6: DATAXFER  AVX512EVEX 62F27D4823C0             vpmovsxwd zmm0, ymm0
XDIS ac: AVX512    AVX512EVEX 62F17D4872F010           vpslld zmm0, zmm0, 0x10
XDIS b3: AVX512    AVX512EVEX 62F1D54858E8             vaddpd zmm5, zmm5, zmm0
XDIS b9: DATAXFER  AVX512EVEX 62F1FF286F00             vmovdqu16 ymm0, ymmword ptr [rax]
XDIS bf: DATAXFER  AVX512EVEX 62F27D4823C0             vpmovsxwd zmm0, ymm0
XDIS c5: AVX512    AVX512EVEX 62F17D4872F010           vpslld zmm0, zmm0, 0x10
XDIS cc: AVX512    AVX512EVEX 62F1CD4858F0             vaddpd zmm6, zmm6, zmm0
XDIS d2: DATAXFER  AVX512EVEX 62F1FF286F00             vmovdqu16 ymm0, ymmword ptr [rax]
XDIS d8: DATAXFER  AVX512EVEX 62F27D4823C0             vpmovsxwd zmm0, ymm0
XDIS de: AVX512    AVX512EVEX 62F17D4872F010           vpslld zmm0, zmm0, 0x10
XDIS e5: AVX512    AVX512EVEX 62F1C54858F8             vaddpd zmm7, zmm7, zmm0
XDIS eb: DATAXFER  AVX512EVEX 62D1FF487F09             vmovdqu16 zmmword ptr [r9], zmm1
XDIS f1: DATAXFER  AVX512EVEX 62D1FF487F5101           vmovdqu16 zmmword ptr [r9+0x40], zmm2
XDIS f8: DATAXFER  AVX512EVEX 62D1FF487F5902           vmovdqu16 zmmword ptr [r9+0x80], zmm3
XDIS ff: DATAXFER  AVX512EVEX 62D1FF487F6103           vmovdqu16 zmmword ptr [r9+0xc0], zmm4
XDIS 106: DATAXFER  AVX512EVEX 62D1FF487F6904           vmovdqu16 zmmword ptr [r9+0x100], zmm5
XDIS 10d: DATAXFER  AVX512EVEX 62D1FF487F7105           vmovdqu16 zmmword ptr [r9+0x140], zmm6
XDIS 114: DATAXFER  AVX512EVEX 62D1FF487F7906           vmovdqu16 zmmword ptr [r9+0x180], zmm7
XDIS 11b: RET       BASE       C3                       ret

**Comment by egeor** [comment]
Yep, will add this check and make sure we return -1

**Comment by egeor** [comment]
Commit e15360aed910fc7504e58659b92bf917b78051c3 should fix this issue.

**Comment by kvoronin-intel** [comment]
Thanks! Closing as https://github.com/libxsmm/libxsmm/commit/1219e74e8f52bee077ea0dfbc291ca069b09461a commit fixed the issue.
