### ISSUE TITLE
A64FX: tool_cpuinfo

### ISSUE THREAD

**Issue by breuera** [libxsmm/libxsmm#737]
https://github.com/libxsmm/libxsmm/blob/3c20980afbf42fa3da88c5581eb6c9f3a27dfb55/scripts/tool_cpuinfo.sh#L23 does not work on A64FX since lscpu does not report "Core(s) per socket".
Fix depends on what the script's "cores" output is supposed to be; cores per NUMA domain?

> [hgf_prd6221@ftp-a64n97 scripts]$ srun -p a64fx lscpu
> Architecture:        aarch64
> Byte Order:          Little Endian
> CPU(s):              48
> On-line CPU(s) list: 0-47
> Thread(s) per core:  1
> Core(s) per cluster: 12
> Socket(s):           -
> Cluster(s):          4
> NUMA node(s):        4
> Vendor ID:           FUJITSU
> Model:               0
> Model name:          A64FX
> Stepping:            0x1
> BogoMIPS:            200.00
> NUMA node0 CPU(s):   0-11
> NUMA node1 CPU(s):   12-23
> NUMA node2 CPU(s):   24-35
> NUMA node3 CPU(s):   36-47
> Flags:               fp asimd evtstrm sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm fcma dcpop sve

**Comment by hfp** [comment]
Interesting, the output I can get looks like:

```text
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              48
On-line CPU(s) list: 0-47
Thread(s) per core:  1
Core(s) per socket:  12
Socket(s):           4
NUMA node(s):        4
Vendor ID:           0x46
Model:               0
Stepping:            0x1
BogoMIPS:            200.00
NUMA node0 CPU(s):   0-11
NUMA node1 CPU(s):   12-23
NUMA node2 CPU(s):   24-35
NUMA node3 CPU(s):   36-47
Flags:               fp asimd evtstrm sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm fcma dcpop sve
```

I will take a look at the issue (`Socket(s): -`).

**Comment by breuera** [comment]
750f828 solved the issue.
