### ISSUE TITLE
aarch64: gemm_kernel_fused misses validation

### ISSUE THREAD

**Issue by hfp** [libxsmm/libxsmm#739]
The `gemm_kernel_fused` misses validation ("sgemm_nt_eqld_bop1_uop2_cvnni0").

A reproducer looks like:

```bash
LIBXSMM_TARGET=aarch64 ./gemm_kernel_fused 15 37 88 15 37 15 1.000000 0.000000 0 0 0 1 nopf F32 nobr 1 0 1 0 1 2 0
```

**Comment by egeor** [comment]
Should be fixed now by 02df5f8343a12d799ad945047d7f0f248914545c
