### ISSUE TITLE
Which interface is the correct one to use openMP multi-threaded batch dgemm?

### ISSUE THREAD

**Issue by HWWH123** [libxsmm/libxsmm#740]
In the interface "libxsmm_gemm_batch_omp" the type of m,n,k is libxsmm_blasint, so I think that means that the matrix groups need to have the same size. But the problem I want to deal with is like 4 groups with different sizes. But when I use libxsmm_dgemm_batch_omp, it happens with segment errors.
So, does libxsmm support batch gemm and support multi-threading like Intel MKL?
https://www.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-c/top/blas-and-sparse-blas-routines/blas-like-extensions/cblas-gemm-batch.html

**Comment by hfp** [comment]
Just for the record: this is related to #642 (issue's answers are outdated).

**Comment by HWWH123** [comment]
> Just for the record: this is related to #642 (issue's answers are outdated).

Yes, but as you say, issue's answers are outdated.

**Comment by hfp** [comment]
> > Just for the record: this is related to #642 (issue's answers are outdated).
> 
> Yes, but as you say, issue's answers are outdated.

Yes, that was to have it linked (and no time for immediate response).

**Comment by hfp** [comment]
Please take a look at https://github.com/libxsmm/libxsmm/tree/main/samples/utilities/wrap. This collection of samples shows LIBXSMM taking calls for `?gemm_batch` and `?gemm_batch_strided`. These are the same interface as MKL provides and LIBXSMM can replace existing calls at static link-time as well per `LD_PRELOAD` (see also `wrap-test.sh` illustrating on how to run). Also, actual matrix shapes are important wrt performance. If this shows some signs of being useful for your cases, it is possible to lower the call overhead of these functions and get rid of the interceptor business (providing an own/dedicated interface). On a further note, the parallelization can be tuned a lot wrt groups of different shapes. However, no one used these functions yet hence I did not put too much effort into.

**Comment by hfp** [comment]
One more comment: we do not have the cblas flavors for any of our functions. For gemm functionality this means triddling the arguments is usually sufficient (like M<->N, A<->B), i.e., no transposes required.

**Comment by hfp** [comment]
Here is an example comparing MKL's `dgemm_batch` and LIBXSMM's implementation of the very same interface:

```bash
cd /path/to/libxsmm; make -j
cd samples/utilities/wrap; make -j
LIBXSMM_VERBOSE=4 OMP_PROC_BIND=close \
  LD_PRELOAD=/path/to/libxsmm/lib/libxsmmext.so \
  LD_LIBRARY_PATH=/path/to/libxsmm/lib:${LD_LIBRARY_PATH} \
./dgemm_batch-blas 24 24 24 24 24 24 20000
```
If you omit the `LD_PRELOAD`, you run the MKL based implementation.

**Comment by hfp** [comment]
Please talk back about whether this is useful or not. I am trying to estimate the "return of invested" time like if there is value for providing high-level interfaces. I believe higher level interfaces need more optimization in the realm of threaded execution rather than optimized kernels. I am not sure right now about balancing effort for a "generic" interface vs "performance left on the table" due to properly threaded code. To clarify, we do not aim to gain little over existing solutions which are potentially highly optimized (like Intel MKL). We want to eventually fill gaps and spear-head for large benefits in certain cases.

**Comment by hfp** [comment]
I am closing this report for now. Please feel free to provide feedback if you get/got to try this functionality.
