### ISSUE TITLE
FsSpMDM: incorrect result on AArch64 baseline

### ISSUE THREAD

**Issue by hfp** [libxsmm/libxsmm#782]
The sparse kernel misses validation because of incorrect results on AArch64 (reproduced on our M1 target). The issue is on the JIT'ted kernel and not the reference value or on the side of the host compiler (checked with both Clang/Apple and GNU based toolchain).

Examples of a reproducer:

```bash
LIBXSMM_FSSPMDM_HINT=1 ./pyfr_driver_asp_reg mats/p1/pri/m460-sp.mtx 48 10
LIBXSMM_FSSPMDM_HINT=1 ./pyfr_driver_asp_reg mats/p1/tet/m460-sp.mtx 48 10
```

The issue is not present on our SVE based code-path.

**Comment by hfp** [comment]
This issue can be reproduced on our Jetson as well as our MacMini/M1 system.

**Comment by FreddieWitherden** [comment]
These matrices have some rows which are all zero.  If I recall this requires special handling.  We have special code for this:

https://github.com/libxsmm/libxsmm/blob/main_stable/src/generator_spgemm_csr_asparse_reg.c#L1216

I have a feeling the issue might be here:

https://github.com/libxsmm/libxsmm/blob/main_stable/src/generator_spgemm_csr_asparse_reg.c#L1243

As something does not look right with this line.

**Comment by FreddieWitherden** [comment]
See PR #788

**Comment by hfp** [comment]
Thank you very much for taking the initiative, your PR fixed the issue!
