### ISSUE TITLE
Issue with shared library installation

### ISSUE THREAD

**Issue by sebastiangrimberg** [libxsmm/libxsmm#783]
When trying to `make PREFIX=$LIBXSMM_PREFIX install` from `main_stable`, I ran into an issue that only the symlink file `libxsmm.dylib` was copied to `$LIBXSMM_PREFIX`, and not the actual versioned `libxsmm.1.dylib` (this is on macOS, using clang 16 to compile). Then, when trying to link programs which use `-lxsmm`, I got linker errors because the installed `libxsmm.dylib` symlinked to the (nonexistent) `libxsmm.1.dylib` in the same folder.

The following change fixes this:

```
diff --git a/Makefile b/Makefile
index 813252dd9..0b629b9b7 100644
--- a/Makefile
+++ b/Makefile
@@ -1361,15 +1361,15 @@ ifneq ($(PREFIX),$(ABSDIR))
        @echo
        @echo "LIBXSMM installing libraries..."
        @$(MKDIR) -p $(PREFIX)/$(POUTDIR)
-       @$(CP) -va $(OUTDIR)/libxsmmnoblas.$(DLIBEXT)* $(PREFIX)/$(POUTDIR) 2>/dev/null || true
+       @$(CP) -va $(OUTDIR)/libxsmmnoblas*.$(DLIBEXT) $(PREFIX)/$(POUTDIR) 2>/dev/null || true
        @$(CP) -v  $(OUTDIR)/libxsmmnoblas.$(SLIBEXT)  $(PREFIX)/$(POUTDIR) 2>/dev/null || true
-       @$(CP) -va $(OUTDIR)/libxsmmgen.$(DLIBEXT)* $(PREFIX)/$(POUTDIR) 2>/dev/null || true
+       @$(CP) -va $(OUTDIR)/libxsmmgen*.$(DLIBEXT) $(PREFIX)/$(POUTDIR) 2>/dev/null || true
        @$(CP) -v  $(OUTDIR)/libxsmmgen.$(SLIBEXT)  $(PREFIX)/$(POUTDIR) 2>/dev/null || true
-       @$(CP) -va $(OUTDIR)/libxsmmext.$(DLIBEXT)* $(PREFIX)/$(POUTDIR) 2>/dev/null || true
+       @$(CP) -va $(OUTDIR)/libxsmmext*.$(DLIBEXT) $(PREFIX)/$(POUTDIR) 2>/dev/null || true
        @$(CP) -v  $(OUTDIR)/libxsmmext.$(SLIBEXT)  $(PREFIX)/$(POUTDIR) 2>/dev/null || true
-       @$(CP) -va $(OUTDIR)/libxsmmf.$(DLIBEXT)* $(PREFIX)/$(POUTDIR) 2>/dev/null || true
+       @$(CP) -va $(OUTDIR)/libxsmmf*.$(DLIBEXT) $(PREFIX)/$(POUTDIR) 2>/dev/null || true
        @$(CP) -v  $(OUTDIR)/libxsmmf.$(SLIBEXT)  $(PREFIX)/$(POUTDIR) 2>/dev/null || true
-       @$(CP) -va $(OUTDIR)/libxsmm.$(DLIBEXT)* $(PREFIX)/$(POUTDIR) 2>/dev/null || true
+       @$(CP) -va $(OUTDIR)/libxsmm*.$(DLIBEXT) $(PREFIX)/$(POUTDIR) 2>/dev/null || true
        @$(CP) -v  $(OUTDIR)/libxsmm.$(SLIBEXT)  $(PREFIX)/$(POUTDIR) 2>/dev/null || true
        @echo
        @echo "LIBXSMM installing pkg-config and module files..."
```

It looks like the asterix was just in the wrong location, but if I am wrong and am instead doing something wrong in my `make install` please let me know. Thank you!

**Comment by hfp** [comment]
**Note**: for new development or integration of LIBXSMM into an application/library, it is advisable to rely on `main` branch. Unfortunately, `main` is temporarily not our default branch, i.e., a fresh clone of LIBXSMM is currently based on `main_stable`. We need the latter only to have easier merge with pending work and to consolidate conflicts into one chunk of work later on. Also, any functions carrying `_v2` as a postfix are recommended. However, `_v2` will be removed when getting closer to LIBXSMM v2.0.

**Comment by hfp** [comment]
Thank you for your report and contribution! I will reproduce and resolve this issue asap.

**Comment by hfp** [comment]
> It looks like the asterix was just in the wrong location

The issue is fixed in `main` and I will be backported to `main_stable` eventually. Regarding `main_stable` vs `main` see also [here](https://github.com/libxsmm/libxsmm/issues/783#issuecomment-1594200631) and [here](https://github.com/libxsmm/libxsmm/wiki/Compatibility#libxsmm-2x). There was a missing asterix rather than an asterix in the wrong place. Though, the location of the library versions (as part of the filename) differs between Linux and MacOS.

**Comment by sebastiangrimberg** [comment]
Thanks for addressing this so quickly! I will switch to the `main` branch, thanks for the tip. Previously (on `main_stable`) I was using `libxsmm_dmmdispatch_v2`/`libxsmm_smmdispatch_v2` to pre-generate `libxsmm_dmmfunction`/`libxsmm_smmfunction` kernels, but it looks like now I should switch to using `libxsmm_dispatch_gemm_v2` to generate a `libxsmm_gemmfunction`. (Looking at [this commit](https://github.com/libxsmm/libxsmm/commit/1f4cdad8dbac3d4e1fd4c2e6b44eaf31238e6e8b) and [this one](https://github.com/libxsmm/libxsmm/commit/9c0e481b08f3eb49b1cf8d1ce377e379e5f6831c). Is my understanding correct?

**Comment by hfp** [comment]
Yes, your understanding is correct (`libxsmm_dispatch_gemm_v2` is the way to go). Indeed, `libxsmm_dmmdispatch_v2` and `libxsmm_smmdispatch_v2` are removed on `main`. They ever carried the v2 postfix only for traditional reasons (BLAS-like type-prefix aka `d` and `s`).

**Comment by sebastiangrimberg** [comment]
Thanks @hfp!

**Comment by hfp** [comment]
I will improve the Wiki page to collect such cases and help transition to v2 (https://github.com/libxsmm/libxsmm/wiki/Compatibility#libxsmm-2x).

**Comment by sebastiangrimberg** [comment]
Hi @hfp, I'm sorry but have another potentially silly question regarding the update to v2 that I thought I might be able to ask here. When I generate a kernel with `libxsmm_dispatch_gemm_v2`, I get a `LIBXSMM ERROR: failed to release kernel!` when I call `libxsmm_release_kernel` on the generated kernel. Is it not required to release the kernels generated with this function? I'm trying to find an example but not seeing much, I'm experimenting with LIBXSMM from libCEED and want to make sure I'm not leaking memory. Thanks again for your help.

**Comment by sebastiangrimberg** [comment]
Awesome! Thank you very much for the detailed explanation @hfp, this is very useful learning.
