### ISSUE TITLE
Tileconfig used uninitialized

### ISSUE THREAD

**Issue by hfp** [libxsmm/libxsmm#787]
See https://github.com/libxsmm/libxsmm/blob/main_stable/src/generator_packed_spgemm_bcsc_bsparse_avx_avx2_avx512_amx.c#L655

**Comment by alheinecke** [comment]
This is fine, TILERELEASE has no arguments.

**Comment by hfp** [comment]
Make sense and then:

```c
      libxsmm_x86_instruction_tile_control( io_generated_code, 0, io_generated_code->arch,
          LIBXSMM_X86_INSTR_TILERELEASE, LIBXSMM_X86_GP_REG_UNDEF, 0, &tile_config );
```

shall change to (definition `libxsmm_tile_config tile_config;` to be removed):

```c
      libxsmm_x86_instruction_tile_control( io_generated_code, 0, io_generated_code->arch,
          LIBXSMM_X86_INSTR_TILERELEASE, LIBXSMM_X86_GP_REG_UNDEF, 0, NULL );
```

to avoid compiler warnings about using uninitialized data.
