### ISSUE TITLE
Where are outputs of kernel scripts after #785

### ISSUE THREAD

**Issue by alheinecke** [libxsmm/libxsmm#789]
#785 brakes my development flows and I cannot find the output scripts anymore.

Scenario running a simple `./kernel_test.sh` in samples/xgemm create all the output files and I could easily look where things break. The files are no longer present. 

We should re-establish the behavior of before #785

**Comment by alheinecke** [comment]
Also I'm not convince that this is what we want: 
  - Limit warning about LIBXSMM_TARGET beyond CPUID to NDEBUG (verbose output), and avoid calling CPUID
    at all if LIBXSMM_TARGET is given. This regime allows easier debugging under ARM (no SIGILL).

**Comment by hfp** [comment]
You can run:

```bash
./kernel_test.sh -o debug.log
```

This will create the logs you had before ("debug.log" is used as filename template for the individual log files).

**Comment by alheinecke** [comment]
`./kernelt_test.sh -o .log`
or 
`./kernelt_test.sh -o *.log`

don't work, so there is some prepend needed?

**Comment by hfp** [comment]
Just `-o filename.ext` or `-o /path/to/file.ext` works. The resulting logfiles follow the pattern `filename-[something].ext`.

**Comment by hfp** [comment]
> Also I'm not convince that this is what we want:
> 
>     * Limit warning about LIBXSMM_TARGET beyond CPUID to NDEBUG (verbose output), and avoid calling CPUID
>       at all if LIBXSMM_TARGET is given. This regime allows easier debugging under ARM (no SIGILL).
>       There under some not CI test platform some rechecks, not sure if they are still functional.

Calling `libxsmm_cpuid()` always performs a check and returns the true resolution (independent of what `LIBXSMM_TARGET` is set to). This is the design of "target" vs "cpuid" (and did not change). The change above is just that if `LIBXSMM_TARGET` is set to something unreasonable, it does not issue a verbose warning. Though, since quite some time we avoid to sanitize or limit the given target (if it was beyond CPUID). The change avoid calling CPUID in the initial library setup and thereby eases debugging code on ARM. We rely on signal handler for SIGILL for CPUID on ARM, which previously required to setup the debugger properly.

**Comment by hfp** [comment]
Regarding logfiles, or specifically for error bounds, you can use `LIBXSMM_MATDIFF=/path/to/file` (which creates or appends to the file) to get one line per call of `libxsmm_matdiff_epsilon` along with the command line of the executable. Such file can be sorted like `sort -gk1 /path/to/file`, e.g., to calibrate error margins.

**Comment by alheinecke** [comment]
I'm just looking for simple script all these knobs I will keep forgetting ;-D , OK got it we have to add some at least one letter before the .log.

For CPUID, does the following still work: I set SPR on a CLX and I will run (when not using some TMUL) or will crash (when using TMUL). Also when I have set SPR, and I run libxsmm_cpuid(), I will get CLX? (at least this is what I understand and what is good)

**Comment by hfp** [comment]
> I set SPR on a CLX and I will run (when not using some TMUL) or will crash (when using TMUL).

Yes, that's the case (user rules). It will crash as soon as an illegal instruction is executed.

> Also when I have set SPR, and I run libxsmm_cpuid(), I will get CLX?

Yes.

**Comment by hfp** [comment]
> I'm just looking for simple script all these knobs I will keep forgetting ;-D

You can also use `./kernel_test.sh -h` (or `--help`), and it will go straight to tool_pexec's help. Most interesting options are:

* `-o`: as described above, logfile template filename. You can also set `export PEXEC_LG=debug.log` to alway generate logs.
* `-u`: generate/update allow-list. All failures are collected into an allow list.

**Comment by hfp** [comment]
> We should re-establish the behavior of before https://github.com/libxsmm/libxsmm/pull/785

The default of the logfile argument changed to `/dev/null` because of slowdown when writing logs in parallel plus spilling files by default into a directory is not very nice. Set export, e.g., `export PEXEC_LG=log.txt` in `.bashrc` and you're back.

**Comment by hfp** [comment]
For further reference, script documentation can be found [here](https://github.com/libxsmm/libxsmm/tree/main/scripts#parallel-execution).
