### ISSUE TITLE
[libxsmm_mmfunction] Assertion error when using LIBXSMM_GEMM_FLAG_TRANS_B and LIBXSMM_GEMM_FLAG_TRANS_AB

### ISSUE THREAD

**Issue by zhongyilin926** [libxsmm/libxsmm#798]
Hello, I was running some code:
```
// Vector initialization
// ...
int M = 1024, N = 768, K = 768;
typedef libxsmm_mmfunction<T> kernel_type;
kernel_type mm_kernel(LIBXSMM_GEMM_FLAG_TRANS_B, M, N, K, 1.0, 0.0);
for (int i = 0; i < B; ++i) {
  mm_kernel(a + (i * M * K), b, c + (i * M * N));
}
```
on an AMD EPYC 16-core CPU (LIBXSMM built with `make AVX=2 BLAS=1 OMP=1`) and got the following error:
```
/home/moderato/workspace/libxsmm/include/libxsmm.h:542: void libxsmm_mmfunction<INP_TYPE, OUT_TYPE, PREFETCH_DEFAULT>::operator()(const itype*, const itype*, libxsmm_mmfunction<INP_TYPE, OUT_TYPE, PREFETCH_DEFAULT>::otype*) const [with INP_TYPE = float; OUT_TYPE = float; int PREFETCH_DEFAULT = -1; libxsmm_mmfunction<INP_TYPE, OUT_TYPE, PREFETCH_DEFAULT>::itype = float; libxsmm_mmfunction<INP_TYPE, OUT_TYPE, PREFETCH_DEFAULT>::otype = float]: Assertion `__null != m_function' failed.
```

LIBXSMM_GEMM_FLAG_TRANS_AB also threw the same error. LIBXSMM_GEMM_FLAG_NONE and LIBXSMM_GEMM_FLAG_TRANS_A are both fine (wrong result though).

I was wondering if anyone could help? Thanks in advance!

**Comment by alheinecke** [comment]
Is this on main_stable or main branch, main_stable is the branch which right now is stabilized.

**Comment by zhongyilin926** [comment]
It's the main_stable branch.

**Comment by alheinecke** [comment]
please share an entire reproducer. I feel, even NONE is broken, that there is a row vs. col major issue in your code.

**Comment by alheinecke** [comment]
I'm closing this issues because of inactivity, feel free to re-open with more details.
