### ISSUE TITLE
CMake build request.

### ISSUE THREAD

**Issue by xuhancn** [libxsmm/libxsmm#826]
I'm working for enable our IPEX CPU on Windows. Our project integrated libxsmm now, and libxsmm was integrated via ExternalProject: https://github.com/intel/intel-extension-for-pytorch/blob/main/csrc/cpu/CMakeLists.txt#L131-L150 . ExternalProject is not cross OS method. 

At the same time, I found libxsmm only provide a MSVC solution file, https://github.com/libxsmm/libxsmm/tree/main/ide . It is not a good practice for CMake project.

Could you please enable origional CMake support for cross OS projects.

**Comment by xuhancn** [comment]
@jgong5

**Comment by jgong5** [comment]
@alheinecke This is about the request for Windows build support for IPEX.

**Comment by alheinecke** [comment]
I'm not sure what you need, libxsmm has no cmake build, neither under windows, nor under Linux. 

However, our MLIR compiler uses cmake and you guys might want to reuse the cmake scripts from there:
https://github.com/plaidml/tpp-mlir/blob/main/cmake/modules/xsmm.cmake

**Comment by jgong5** [comment]
> I'm not sure what you need, libxsmm has no cmake build, neither under windows, nor under Linux.
> 
> However, our MLIR compiler uses cmake and you guys might want to reuse the cmake scripts from there: https://github.com/plaidml/tpp-mlir/blob/main/cmake/modules/xsmm.cmake

@alheinecke Thanks for the pointer. @xuhancn Are we able to use the cmake to build libxsmm in IPEX?

**Comment by xuhancn** [comment]
> I'm not sure what you need, libxsmm has no cmake build, neither under windows, nor under Linux.
> 
> However, our MLIR compiler uses cmake and you guys might want to reuse the cmake scripts from there: https://github.com/plaidml/tpp-mlir/blob/main/cmake/modules/xsmm.cmake

I still suggest you enable CMake in your libxsmm project.

1. On Windows, the MSVC solution file is limited MSVC version and runtime library version. CMake can solve this issue and genarate solution file on demand.
2. It is not bad MLIR has a example cmake file. But the parent project contains submodule's cmake, it is strange. I suggest move the example cmake file to libxsmm, it is the make sense solution.

**Comment by alheinecke** [comment]
We have no plan for supporting cmake, but you are more than welcome to submit a PR with cmake support.

**Comment by xuhancn** [comment]
> We have no plan for supporting cmake, but you are more than welcome to submit a PR with cmake support.

https://github.com/libxsmm/libxsmm/pull/827 PR is here, Pls review it. @alheinecke , CC @jgong5
