### ISSUE TITLE
Gemv with libxsmm

### ISSUE THREAD

**Issue by akote123** [libxsmm/libxsmm#901]
How to create kernel for libxsmm gemv(similar to kernel_type kernel(LIBXSMM_GEMM_FLAG_NONE, m, n, k, 1.0 /*alpha*/, 1.0 /*beta*/);) or depending on the shapes the gemm is redirected gemv internally?

**Comment by hfp** [comment]
> able to run gemv with libxsmm_sgemv_function sgemv = libxsmm_original_sgemv();

This is not a kernel generated by LIBXSMM's code generation but a function returning a function-pointer to a related BLAS function (gemv). Let's discuss further what you wanted to achieve!

**Comment by akote123** [comment]
> > able to run gemv with libxsmm_sgemv_function sgemv = libxsmm_original_sgemv();
> 
> This is not a kernel generated by LIBXSMM's code generation but a function returning a function-pointer to a related BLAS function (gemv). Let's discuss further what you wanted to achieve!



> > able to run gemv with libxsmm_sgemv_function sgemv = libxsmm_original_sgemv();
> 
> This is not a kernel generated by LIBXSMM's code generation but a function returning a function-pointer to a related BLAS function (gemv). Let's discuss further what you wanted to achieve!

Then this function is pointed to openblas gemv ?

**Comment by alheinecke** [comment]
You use GEMM and set N=1 and then you have GEMV. Since GEMV is bandwidth bound the value of LIBXSMM will low.

**Comment by hfp** [comment]
> > > able to run gemv with libxsmm_sgemv_function sgemv = libxsmm_original_sgemv();
> > 
> > 
> > This is not a kernel generated by LIBXSMM's code generation but a function returning a function-pointer to a related BLAS function (gemv). Let's discuss further what you wanted to achieve!
> 
> > > able to run gemv with libxsmm_sgemv_function sgemv = libxsmm_original_sgemv();
> > 
> > 
> > This is not a kernel generated by LIBXSMM's code generation but a function returning a function-pointer to a related BLAS function (gemv). Let's discuss further what you wanted to achieve!
> 
> Then this function is pointed to openblas gemv ?

Simply said, yes but it's not actually intended for consumption (since one can call OpenBLAS or BLAS in general). It's part of the call-wrapper/interceptor code.

**Comment by hfp** [comment]
> You use GEMM and set N=1 and then you have GEMV. Since GEMV is bandwidth bound the value of LIBXSMM will be low.

As Alex said, GEMV is a degenerated GEMM and LIBXSMM brings little/nothing to the table.

**Comment by akote123** [comment]
@alheinecke and @hfp  Thank you.
